// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ctpview-trader.proto

#include "ctpview-trader.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ctpview_trader {
PROTOBUF_CONSTEXPR message::message(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.MessageType_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct messageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR messageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~messageDefaultTypeInternal() {}
  union {
    message _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 messageDefaultTypeInternal _message_default_instance_;
PROTOBUF_CONSTEXPR LoginControl::LoginControl(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.command_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LoginControlDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginControlDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginControlDefaultTypeInternal() {}
  union {
    LoginControl _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginControlDefaultTypeInternal _LoginControl_default_instance_;
PROTOBUF_CONSTEXPR BugInjection::BugInjection(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BugInjectionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BugInjectionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BugInjectionDefaultTypeInternal() {}
  union {
    BugInjection _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BugInjectionDefaultTypeInternal _BugInjection_default_instance_;
PROTOBUF_CONSTEXPR ProfilerControl::ProfilerControl(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.profiler_action_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProfilerControlDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProfilerControlDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProfilerControlDefaultTypeInternal() {}
  union {
    ProfilerControl _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProfilerControlDefaultTypeInternal _ProfilerControl_default_instance_;
PROTOBUF_CONSTEXPR UpdatePara::UpdatePara(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.update_action_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UpdateParaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateParaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateParaDefaultTypeInternal() {}
  union {
    UpdatePara _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateParaDefaultTypeInternal _UpdatePara_default_instance_;
PROTOBUF_CONSTEXPR ClearDiagnosticEvent::ClearDiagnosticEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.diagnostic_event_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ClearDiagnosticEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClearDiagnosticEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClearDiagnosticEventDefaultTypeInternal() {}
  union {
    ClearDiagnosticEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClearDiagnosticEventDefaultTypeInternal _ClearDiagnosticEvent_default_instance_;
PROTOBUF_CONSTEXPR SendTestEmail::SendTestEmail(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.send_action_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SendTestEmailDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SendTestEmailDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SendTestEmailDefaultTypeInternal() {}
  union {
    SendTestEmail _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SendTestEmailDefaultTypeInternal _SendTestEmail_default_instance_;
PROTOBUF_CONSTEXPR UpdateAccountGroup::UpdateAccountGroup(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.account_)*/{}
  , /*decltype(_impl_.group_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UpdateAccountGroupDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateAccountGroupDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateAccountGroupDefaultTypeInternal() {}
  union {
    UpdateAccountGroup _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateAccountGroupDefaultTypeInternal _UpdateAccountGroup_default_instance_;
}  // namespace ctpview_trader
static ::_pb::Metadata file_level_metadata_ctpview_2dtrader_2eproto[8];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ctpview_2dtrader_2eproto[5];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ctpview_2dtrader_2eproto = nullptr;

const uint32_t TableStruct_ctpview_2dtrader_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::message, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::message, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::message, _impl_.MessageType_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::LoginControl, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::LoginControl, _impl_.command_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::BugInjection, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::BugInjection, _impl_.type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::ProfilerControl, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::ProfilerControl, _impl_.profiler_action_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::UpdatePara, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::UpdatePara, _impl_.update_action_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::ClearDiagnosticEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::ClearDiagnosticEvent, _impl_.diagnostic_event_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::SendTestEmail, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::SendTestEmail, _impl_.send_action_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::UpdateAccountGroup, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::UpdateAccountGroup, _impl_.group_id_),
  PROTOBUF_FIELD_OFFSET(::ctpview_trader::UpdateAccountGroup, _impl_.account_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ctpview_trader::message)},
  { 14, -1, -1, sizeof(::ctpview_trader::LoginControl)},
  { 21, -1, -1, sizeof(::ctpview_trader::BugInjection)},
  { 28, -1, -1, sizeof(::ctpview_trader::ProfilerControl)},
  { 35, -1, -1, sizeof(::ctpview_trader::UpdatePara)},
  { 42, -1, -1, sizeof(::ctpview_trader::ClearDiagnosticEvent)},
  { 49, -1, -1, sizeof(::ctpview_trader::SendTestEmail)},
  { 56, -1, -1, sizeof(::ctpview_trader::UpdateAccountGroup)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ctpview_trader::_message_default_instance_._instance,
  &::ctpview_trader::_LoginControl_default_instance_._instance,
  &::ctpview_trader::_BugInjection_default_instance_._instance,
  &::ctpview_trader::_ProfilerControl_default_instance_._instance,
  &::ctpview_trader::_UpdatePara_default_instance_._instance,
  &::ctpview_trader::_ClearDiagnosticEvent_default_instance_._instance,
  &::ctpview_trader::_SendTestEmail_default_instance_._instance,
  &::ctpview_trader::_UpdateAccountGroup_default_instance_._instance,
};

const char descriptor_table_protodef_ctpview_2dtrader_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024ctpview-trader.proto\022\016ctpview_trader\"\267"
  "\003\n\007message\0225\n\rlogin_control\030\001 \001(\0132\034.ctpv"
  "iew_trader.LoginControlH\000\0225\n\rbug_injecti"
  "on\030\002 \001(\0132\034.ctpview_trader.BugInjectionH\000"
  "\022;\n\020profiler_control\030\003 \001(\0132\037.ctpview_tra"
  "der.ProfilerControlH\000\0221\n\013update_para\030\004 \001"
  "(\0132\032.ctpview_trader.UpdateParaH\000\022F\n\026clea"
  "r_diagnostic_event\030\005 \001(\0132$.ctpview_trade"
  "r.ClearDiagnosticEventH\000\0223\n\nsend_email\030\006"
  " \001(\0132\035.ctpview_trader.SendTestEmailH\000\022B\n"
  "\024update_account_group\030\007 \001(\0132\".ctpview_tr"
  "ader.UpdateAccountGroupH\000B\r\n\013MessageType"
  "\"t\n\014LoginControl\0225\n\007command\030\001 \001(\0162$.ctpv"
  "iew_trader.LoginControl.Command\"-\n\007Comma"
  "nd\022\013\n\007reserve\020\000\022\t\n\005login\020\001\022\n\n\006logout\020\002\"w"
  "\n\014BugInjection\0228\n\004type\030\001 \001(\0162*.ctpview_t"
  "rader.BugInjection.InjectionType\"-\n\rInje"
  "ctionType\022\013\n\007reserve\020\000\022\017\n\013double_free\020\001\""
  "\232\001\n\017ProfilerControl\022G\n\017profiler_action\030\001"
  " \001(\0162..ctpview_trader.ProfilerControl.Pr"
  "ofilerAction\">\n\016ProfilerAction\022\013\n\007reserv"
  "e\020\000\022\017\n\013start_write\020\001\022\016\n\nstop_write\020\002\"\203\001\n"
  "\nUpdatePara\022>\n\rupdate_action\030\001 \001(\0162\'.ctp"
  "view_trader.UpdatePara.UpdateAction\"5\n\014U"
  "pdateAction\022\013\n\007reserve\020\000\022\n\n\006update\020\001\022\014\n\010"
  "noupdate\020\002\"3\n\024ClearDiagnosticEvent\022\033\n\023di"
  "agnostic_event_id\030\001 \001(\r\"\177\n\rSendTestEmail"
  "\022=\n\013send_action\030\001 \001(\0162(.ctpview_trader.S"
  "endTestEmail.SendAction\"/\n\nSendAction\022\013\n"
  "\007reserve\020\000\022\010\n\004send\020\001\022\n\n\006nosend\020\002\"7\n\022Upda"
  "teAccountGroup\022\020\n\010group_id\030\001 \001(\t\022\017\n\007acco"
  "unt\030\002 \003(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ctpview_2dtrader_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ctpview_2dtrader_2eproto = {
    false, false, 1257, descriptor_table_protodef_ctpview_2dtrader_2eproto,
    "ctpview-trader.proto",
    &descriptor_table_ctpview_2dtrader_2eproto_once, nullptr, 0, 8,
    schemas, file_default_instances, TableStruct_ctpview_2dtrader_2eproto::offsets,
    file_level_metadata_ctpview_2dtrader_2eproto, file_level_enum_descriptors_ctpview_2dtrader_2eproto,
    file_level_service_descriptors_ctpview_2dtrader_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ctpview_2dtrader_2eproto_getter() {
  return &descriptor_table_ctpview_2dtrader_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ctpview_2dtrader_2eproto(&descriptor_table_ctpview_2dtrader_2eproto);
namespace ctpview_trader {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LoginControl_Command_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ctpview_2dtrader_2eproto);
  return file_level_enum_descriptors_ctpview_2dtrader_2eproto[0];
}
bool LoginControl_Command_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr LoginControl_Command LoginControl::reserve;
constexpr LoginControl_Command LoginControl::login;
constexpr LoginControl_Command LoginControl::logout;
constexpr LoginControl_Command LoginControl::Command_MIN;
constexpr LoginControl_Command LoginControl::Command_MAX;
constexpr int LoginControl::Command_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BugInjection_InjectionType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ctpview_2dtrader_2eproto);
  return file_level_enum_descriptors_ctpview_2dtrader_2eproto[1];
}
bool BugInjection_InjectionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr BugInjection_InjectionType BugInjection::reserve;
constexpr BugInjection_InjectionType BugInjection::double_free;
constexpr BugInjection_InjectionType BugInjection::InjectionType_MIN;
constexpr BugInjection_InjectionType BugInjection::InjectionType_MAX;
constexpr int BugInjection::InjectionType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ProfilerControl_ProfilerAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ctpview_2dtrader_2eproto);
  return file_level_enum_descriptors_ctpview_2dtrader_2eproto[2];
}
bool ProfilerControl_ProfilerAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr ProfilerControl_ProfilerAction ProfilerControl::reserve;
constexpr ProfilerControl_ProfilerAction ProfilerControl::start_write;
constexpr ProfilerControl_ProfilerAction ProfilerControl::stop_write;
constexpr ProfilerControl_ProfilerAction ProfilerControl::ProfilerAction_MIN;
constexpr ProfilerControl_ProfilerAction ProfilerControl::ProfilerAction_MAX;
constexpr int ProfilerControl::ProfilerAction_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UpdatePara_UpdateAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ctpview_2dtrader_2eproto);
  return file_level_enum_descriptors_ctpview_2dtrader_2eproto[3];
}
bool UpdatePara_UpdateAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr UpdatePara_UpdateAction UpdatePara::reserve;
constexpr UpdatePara_UpdateAction UpdatePara::update;
constexpr UpdatePara_UpdateAction UpdatePara::noupdate;
constexpr UpdatePara_UpdateAction UpdatePara::UpdateAction_MIN;
constexpr UpdatePara_UpdateAction UpdatePara::UpdateAction_MAX;
constexpr int UpdatePara::UpdateAction_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SendTestEmail_SendAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ctpview_2dtrader_2eproto);
  return file_level_enum_descriptors_ctpview_2dtrader_2eproto[4];
}
bool SendTestEmail_SendAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr SendTestEmail_SendAction SendTestEmail::reserve;
constexpr SendTestEmail_SendAction SendTestEmail::send;
constexpr SendTestEmail_SendAction SendTestEmail::nosend;
constexpr SendTestEmail_SendAction SendTestEmail::SendAction_MIN;
constexpr SendTestEmail_SendAction SendTestEmail::SendAction_MAX;
constexpr int SendTestEmail::SendAction_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class message::_Internal {
 public:
  static const ::ctpview_trader::LoginControl& login_control(const message* msg);
  static const ::ctpview_trader::BugInjection& bug_injection(const message* msg);
  static const ::ctpview_trader::ProfilerControl& profiler_control(const message* msg);
  static const ::ctpview_trader::UpdatePara& update_para(const message* msg);
  static const ::ctpview_trader::ClearDiagnosticEvent& clear_diagnostic_event(const message* msg);
  static const ::ctpview_trader::SendTestEmail& send_email(const message* msg);
  static const ::ctpview_trader::UpdateAccountGroup& update_account_group(const message* msg);
};

const ::ctpview_trader::LoginControl&
message::_Internal::login_control(const message* msg) {
  return *msg->_impl_.MessageType_.login_control_;
}
const ::ctpview_trader::BugInjection&
message::_Internal::bug_injection(const message* msg) {
  return *msg->_impl_.MessageType_.bug_injection_;
}
const ::ctpview_trader::ProfilerControl&
message::_Internal::profiler_control(const message* msg) {
  return *msg->_impl_.MessageType_.profiler_control_;
}
const ::ctpview_trader::UpdatePara&
message::_Internal::update_para(const message* msg) {
  return *msg->_impl_.MessageType_.update_para_;
}
const ::ctpview_trader::ClearDiagnosticEvent&
message::_Internal::clear_diagnostic_event(const message* msg) {
  return *msg->_impl_.MessageType_.clear_diagnostic_event_;
}
const ::ctpview_trader::SendTestEmail&
message::_Internal::send_email(const message* msg) {
  return *msg->_impl_.MessageType_.send_email_;
}
const ::ctpview_trader::UpdateAccountGroup&
message::_Internal::update_account_group(const message* msg) {
  return *msg->_impl_.MessageType_.update_account_group_;
}
void message::set_allocated_login_control(::ctpview_trader::LoginControl* login_control) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (login_control) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(login_control);
    if (message_arena != submessage_arena) {
      login_control = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, login_control, submessage_arena);
    }
    set_has_login_control();
    _impl_.MessageType_.login_control_ = login_control;
  }
  // @@protoc_insertion_point(field_set_allocated:ctpview_trader.message.login_control)
}
void message::set_allocated_bug_injection(::ctpview_trader::BugInjection* bug_injection) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (bug_injection) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(bug_injection);
    if (message_arena != submessage_arena) {
      bug_injection = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, bug_injection, submessage_arena);
    }
    set_has_bug_injection();
    _impl_.MessageType_.bug_injection_ = bug_injection;
  }
  // @@protoc_insertion_point(field_set_allocated:ctpview_trader.message.bug_injection)
}
void message::set_allocated_profiler_control(::ctpview_trader::ProfilerControl* profiler_control) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (profiler_control) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(profiler_control);
    if (message_arena != submessage_arena) {
      profiler_control = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, profiler_control, submessage_arena);
    }
    set_has_profiler_control();
    _impl_.MessageType_.profiler_control_ = profiler_control;
  }
  // @@protoc_insertion_point(field_set_allocated:ctpview_trader.message.profiler_control)
}
void message::set_allocated_update_para(::ctpview_trader::UpdatePara* update_para) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (update_para) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(update_para);
    if (message_arena != submessage_arena) {
      update_para = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, update_para, submessage_arena);
    }
    set_has_update_para();
    _impl_.MessageType_.update_para_ = update_para;
  }
  // @@protoc_insertion_point(field_set_allocated:ctpview_trader.message.update_para)
}
void message::set_allocated_clear_diagnostic_event(::ctpview_trader::ClearDiagnosticEvent* clear_diagnostic_event) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (clear_diagnostic_event) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(clear_diagnostic_event);
    if (message_arena != submessage_arena) {
      clear_diagnostic_event = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, clear_diagnostic_event, submessage_arena);
    }
    set_has_clear_diagnostic_event();
    _impl_.MessageType_.clear_diagnostic_event_ = clear_diagnostic_event;
  }
  // @@protoc_insertion_point(field_set_allocated:ctpview_trader.message.clear_diagnostic_event)
}
void message::set_allocated_send_email(::ctpview_trader::SendTestEmail* send_email) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (send_email) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(send_email);
    if (message_arena != submessage_arena) {
      send_email = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, send_email, submessage_arena);
    }
    set_has_send_email();
    _impl_.MessageType_.send_email_ = send_email;
  }
  // @@protoc_insertion_point(field_set_allocated:ctpview_trader.message.send_email)
}
void message::set_allocated_update_account_group(::ctpview_trader::UpdateAccountGroup* update_account_group) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (update_account_group) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(update_account_group);
    if (message_arena != submessage_arena) {
      update_account_group = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, update_account_group, submessage_arena);
    }
    set_has_update_account_group();
    _impl_.MessageType_.update_account_group_ = update_account_group;
  }
  // @@protoc_insertion_point(field_set_allocated:ctpview_trader.message.update_account_group)
}
message::message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ctpview_trader.message)
}
message::message(const message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  message* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.MessageType_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_MessageType();
  switch (from.MessageType_case()) {
    case kLoginControl: {
      _this->_internal_mutable_login_control()->::ctpview_trader::LoginControl::MergeFrom(
          from._internal_login_control());
      break;
    }
    case kBugInjection: {
      _this->_internal_mutable_bug_injection()->::ctpview_trader::BugInjection::MergeFrom(
          from._internal_bug_injection());
      break;
    }
    case kProfilerControl: {
      _this->_internal_mutable_profiler_control()->::ctpview_trader::ProfilerControl::MergeFrom(
          from._internal_profiler_control());
      break;
    }
    case kUpdatePara: {
      _this->_internal_mutable_update_para()->::ctpview_trader::UpdatePara::MergeFrom(
          from._internal_update_para());
      break;
    }
    case kClearDiagnosticEvent: {
      _this->_internal_mutable_clear_diagnostic_event()->::ctpview_trader::ClearDiagnosticEvent::MergeFrom(
          from._internal_clear_diagnostic_event());
      break;
    }
    case kSendEmail: {
      _this->_internal_mutable_send_email()->::ctpview_trader::SendTestEmail::MergeFrom(
          from._internal_send_email());
      break;
    }
    case kUpdateAccountGroup: {
      _this->_internal_mutable_update_account_group()->::ctpview_trader::UpdateAccountGroup::MergeFrom(
          from._internal_update_account_group());
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:ctpview_trader.message)
}

inline void message::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.MessageType_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_MessageType();
}

message::~message() {
  // @@protoc_insertion_point(destructor:ctpview_trader.message)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void message::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_MessageType()) {
    clear_MessageType();
  }
}

void message::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void message::clear_MessageType() {
// @@protoc_insertion_point(one_of_clear_start:ctpview_trader.message)
  switch (MessageType_case()) {
    case kLoginControl: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.login_control_;
      }
      break;
    }
    case kBugInjection: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.bug_injection_;
      }
      break;
    }
    case kProfilerControl: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.profiler_control_;
      }
      break;
    }
    case kUpdatePara: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.update_para_;
      }
      break;
    }
    case kClearDiagnosticEvent: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.clear_diagnostic_event_;
      }
      break;
    }
    case kSendEmail: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.send_email_;
      }
      break;
    }
    case kUpdateAccountGroup: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.update_account_group_;
      }
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = MESSAGETYPE_NOT_SET;
}


void message::Clear() {
// @@protoc_insertion_point(message_clear_start:ctpview_trader.message)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_MessageType();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* message::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ctpview_trader.LoginControl login_control = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_login_control(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ctpview_trader.BugInjection bug_injection = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_bug_injection(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ctpview_trader.ProfilerControl profiler_control = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_profiler_control(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ctpview_trader.UpdatePara update_para = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_update_para(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ctpview_trader.ClearDiagnosticEvent clear_diagnostic_event = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_clear_diagnostic_event(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ctpview_trader.SendTestEmail send_email = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_send_email(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ctpview_trader.UpdateAccountGroup update_account_group = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_update_account_group(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* message::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ctpview_trader.message)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ctpview_trader.LoginControl login_control = 1;
  if (_internal_has_login_control()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::login_control(this),
        _Internal::login_control(this).GetCachedSize(), target, stream);
  }

  // .ctpview_trader.BugInjection bug_injection = 2;
  if (_internal_has_bug_injection()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::bug_injection(this),
        _Internal::bug_injection(this).GetCachedSize(), target, stream);
  }

  // .ctpview_trader.ProfilerControl profiler_control = 3;
  if (_internal_has_profiler_control()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::profiler_control(this),
        _Internal::profiler_control(this).GetCachedSize(), target, stream);
  }

  // .ctpview_trader.UpdatePara update_para = 4;
  if (_internal_has_update_para()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::update_para(this),
        _Internal::update_para(this).GetCachedSize(), target, stream);
  }

  // .ctpview_trader.ClearDiagnosticEvent clear_diagnostic_event = 5;
  if (_internal_has_clear_diagnostic_event()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::clear_diagnostic_event(this),
        _Internal::clear_diagnostic_event(this).GetCachedSize(), target, stream);
  }

  // .ctpview_trader.SendTestEmail send_email = 6;
  if (_internal_has_send_email()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::send_email(this),
        _Internal::send_email(this).GetCachedSize(), target, stream);
  }

  // .ctpview_trader.UpdateAccountGroup update_account_group = 7;
  if (_internal_has_update_account_group()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::update_account_group(this),
        _Internal::update_account_group(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ctpview_trader.message)
  return target;
}

size_t message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ctpview_trader.message)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (MessageType_case()) {
    // .ctpview_trader.LoginControl login_control = 1;
    case kLoginControl: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.login_control_);
      break;
    }
    // .ctpview_trader.BugInjection bug_injection = 2;
    case kBugInjection: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.bug_injection_);
      break;
    }
    // .ctpview_trader.ProfilerControl profiler_control = 3;
    case kProfilerControl: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.profiler_control_);
      break;
    }
    // .ctpview_trader.UpdatePara update_para = 4;
    case kUpdatePara: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.update_para_);
      break;
    }
    // .ctpview_trader.ClearDiagnosticEvent clear_diagnostic_event = 5;
    case kClearDiagnosticEvent: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.clear_diagnostic_event_);
      break;
    }
    // .ctpview_trader.SendTestEmail send_email = 6;
    case kSendEmail: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.send_email_);
      break;
    }
    // .ctpview_trader.UpdateAccountGroup update_account_group = 7;
    case kUpdateAccountGroup: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.update_account_group_);
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData message::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    message::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*message::GetClassData() const { return &_class_data_; }


void message::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<message*>(&to_msg);
  auto& from = static_cast<const message&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ctpview_trader.message)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.MessageType_case()) {
    case kLoginControl: {
      _this->_internal_mutable_login_control()->::ctpview_trader::LoginControl::MergeFrom(
          from._internal_login_control());
      break;
    }
    case kBugInjection: {
      _this->_internal_mutable_bug_injection()->::ctpview_trader::BugInjection::MergeFrom(
          from._internal_bug_injection());
      break;
    }
    case kProfilerControl: {
      _this->_internal_mutable_profiler_control()->::ctpview_trader::ProfilerControl::MergeFrom(
          from._internal_profiler_control());
      break;
    }
    case kUpdatePara: {
      _this->_internal_mutable_update_para()->::ctpview_trader::UpdatePara::MergeFrom(
          from._internal_update_para());
      break;
    }
    case kClearDiagnosticEvent: {
      _this->_internal_mutable_clear_diagnostic_event()->::ctpview_trader::ClearDiagnosticEvent::MergeFrom(
          from._internal_clear_diagnostic_event());
      break;
    }
    case kSendEmail: {
      _this->_internal_mutable_send_email()->::ctpview_trader::SendTestEmail::MergeFrom(
          from._internal_send_email());
      break;
    }
    case kUpdateAccountGroup: {
      _this->_internal_mutable_update_account_group()->::ctpview_trader::UpdateAccountGroup::MergeFrom(
          from._internal_update_account_group());
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void message::CopyFrom(const message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ctpview_trader.message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool message::IsInitialized() const {
  return true;
}

void message::InternalSwap(message* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.MessageType_, other->_impl_.MessageType_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata message::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ctpview_2dtrader_2eproto_getter, &descriptor_table_ctpview_2dtrader_2eproto_once,
      file_level_metadata_ctpview_2dtrader_2eproto[0]);
}

// ===================================================================

class LoginControl::_Internal {
 public:
};

LoginControl::LoginControl(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ctpview_trader.LoginControl)
}
LoginControl::LoginControl(const LoginControl& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LoginControl* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.command_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.command_ = from._impl_.command_;
  // @@protoc_insertion_point(copy_constructor:ctpview_trader.LoginControl)
}

inline void LoginControl::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.command_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

LoginControl::~LoginControl() {
  // @@protoc_insertion_point(destructor:ctpview_trader.LoginControl)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LoginControl::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void LoginControl::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LoginControl::Clear() {
// @@protoc_insertion_point(message_clear_start:ctpview_trader.LoginControl)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.command_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LoginControl::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ctpview_trader.LoginControl.Command command = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_command(static_cast<::ctpview_trader::LoginControl_Command>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LoginControl::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ctpview_trader.LoginControl)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ctpview_trader.LoginControl.Command command = 1;
  if (this->_internal_command() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_command(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ctpview_trader.LoginControl)
  return target;
}

size_t LoginControl::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ctpview_trader.LoginControl)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ctpview_trader.LoginControl.Command command = 1;
  if (this->_internal_command() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_command());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LoginControl::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LoginControl::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LoginControl::GetClassData() const { return &_class_data_; }


void LoginControl::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LoginControl*>(&to_msg);
  auto& from = static_cast<const LoginControl&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ctpview_trader.LoginControl)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_command() != 0) {
    _this->_internal_set_command(from._internal_command());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LoginControl::CopyFrom(const LoginControl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ctpview_trader.LoginControl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginControl::IsInitialized() const {
  return true;
}

void LoginControl::InternalSwap(LoginControl* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.command_, other->_impl_.command_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LoginControl::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ctpview_2dtrader_2eproto_getter, &descriptor_table_ctpview_2dtrader_2eproto_once,
      file_level_metadata_ctpview_2dtrader_2eproto[1]);
}

// ===================================================================

class BugInjection::_Internal {
 public:
};

BugInjection::BugInjection(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ctpview_trader.BugInjection)
}
BugInjection::BugInjection(const BugInjection& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BugInjection* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.type_ = from._impl_.type_;
  // @@protoc_insertion_point(copy_constructor:ctpview_trader.BugInjection)
}

inline void BugInjection::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BugInjection::~BugInjection() {
  // @@protoc_insertion_point(destructor:ctpview_trader.BugInjection)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BugInjection::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BugInjection::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BugInjection::Clear() {
// @@protoc_insertion_point(message_clear_start:ctpview_trader.BugInjection)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BugInjection::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ctpview_trader.BugInjection.InjectionType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::ctpview_trader::BugInjection_InjectionType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BugInjection::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ctpview_trader.BugInjection)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ctpview_trader.BugInjection.InjectionType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ctpview_trader.BugInjection)
  return target;
}

size_t BugInjection::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ctpview_trader.BugInjection)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ctpview_trader.BugInjection.InjectionType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BugInjection::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BugInjection::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BugInjection::GetClassData() const { return &_class_data_; }


void BugInjection::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BugInjection*>(&to_msg);
  auto& from = static_cast<const BugInjection&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ctpview_trader.BugInjection)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BugInjection::CopyFrom(const BugInjection& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ctpview_trader.BugInjection)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BugInjection::IsInitialized() const {
  return true;
}

void BugInjection::InternalSwap(BugInjection* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BugInjection::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ctpview_2dtrader_2eproto_getter, &descriptor_table_ctpview_2dtrader_2eproto_once,
      file_level_metadata_ctpview_2dtrader_2eproto[2]);
}

// ===================================================================

class ProfilerControl::_Internal {
 public:
};

ProfilerControl::ProfilerControl(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ctpview_trader.ProfilerControl)
}
ProfilerControl::ProfilerControl(const ProfilerControl& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProfilerControl* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.profiler_action_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.profiler_action_ = from._impl_.profiler_action_;
  // @@protoc_insertion_point(copy_constructor:ctpview_trader.ProfilerControl)
}

inline void ProfilerControl::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.profiler_action_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProfilerControl::~ProfilerControl() {
  // @@protoc_insertion_point(destructor:ctpview_trader.ProfilerControl)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProfilerControl::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ProfilerControl::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProfilerControl::Clear() {
// @@protoc_insertion_point(message_clear_start:ctpview_trader.ProfilerControl)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.profiler_action_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProfilerControl::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ctpview_trader.ProfilerControl.ProfilerAction profiler_action = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_profiler_action(static_cast<::ctpview_trader::ProfilerControl_ProfilerAction>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProfilerControl::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ctpview_trader.ProfilerControl)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ctpview_trader.ProfilerControl.ProfilerAction profiler_action = 1;
  if (this->_internal_profiler_action() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_profiler_action(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ctpview_trader.ProfilerControl)
  return target;
}

size_t ProfilerControl::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ctpview_trader.ProfilerControl)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ctpview_trader.ProfilerControl.ProfilerAction profiler_action = 1;
  if (this->_internal_profiler_action() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_profiler_action());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProfilerControl::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProfilerControl::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProfilerControl::GetClassData() const { return &_class_data_; }


void ProfilerControl::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProfilerControl*>(&to_msg);
  auto& from = static_cast<const ProfilerControl&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ctpview_trader.ProfilerControl)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_profiler_action() != 0) {
    _this->_internal_set_profiler_action(from._internal_profiler_action());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProfilerControl::CopyFrom(const ProfilerControl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ctpview_trader.ProfilerControl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProfilerControl::IsInitialized() const {
  return true;
}

void ProfilerControl::InternalSwap(ProfilerControl* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.profiler_action_, other->_impl_.profiler_action_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProfilerControl::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ctpview_2dtrader_2eproto_getter, &descriptor_table_ctpview_2dtrader_2eproto_once,
      file_level_metadata_ctpview_2dtrader_2eproto[3]);
}

// ===================================================================

class UpdatePara::_Internal {
 public:
};

UpdatePara::UpdatePara(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ctpview_trader.UpdatePara)
}
UpdatePara::UpdatePara(const UpdatePara& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpdatePara* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.update_action_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.update_action_ = from._impl_.update_action_;
  // @@protoc_insertion_point(copy_constructor:ctpview_trader.UpdatePara)
}

inline void UpdatePara::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.update_action_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UpdatePara::~UpdatePara() {
  // @@protoc_insertion_point(destructor:ctpview_trader.UpdatePara)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpdatePara::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void UpdatePara::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpdatePara::Clear() {
// @@protoc_insertion_point(message_clear_start:ctpview_trader.UpdatePara)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.update_action_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdatePara::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ctpview_trader.UpdatePara.UpdateAction update_action = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_update_action(static_cast<::ctpview_trader::UpdatePara_UpdateAction>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UpdatePara::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ctpview_trader.UpdatePara)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ctpview_trader.UpdatePara.UpdateAction update_action = 1;
  if (this->_internal_update_action() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_update_action(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ctpview_trader.UpdatePara)
  return target;
}

size_t UpdatePara::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ctpview_trader.UpdatePara)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ctpview_trader.UpdatePara.UpdateAction update_action = 1;
  if (this->_internal_update_action() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_update_action());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdatePara::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpdatePara::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdatePara::GetClassData() const { return &_class_data_; }


void UpdatePara::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpdatePara*>(&to_msg);
  auto& from = static_cast<const UpdatePara&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ctpview_trader.UpdatePara)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_update_action() != 0) {
    _this->_internal_set_update_action(from._internal_update_action());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdatePara::CopyFrom(const UpdatePara& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ctpview_trader.UpdatePara)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdatePara::IsInitialized() const {
  return true;
}

void UpdatePara::InternalSwap(UpdatePara* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.update_action_, other->_impl_.update_action_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdatePara::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ctpview_2dtrader_2eproto_getter, &descriptor_table_ctpview_2dtrader_2eproto_once,
      file_level_metadata_ctpview_2dtrader_2eproto[4]);
}

// ===================================================================

class ClearDiagnosticEvent::_Internal {
 public:
};

ClearDiagnosticEvent::ClearDiagnosticEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ctpview_trader.ClearDiagnosticEvent)
}
ClearDiagnosticEvent::ClearDiagnosticEvent(const ClearDiagnosticEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ClearDiagnosticEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.diagnostic_event_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.diagnostic_event_id_ = from._impl_.diagnostic_event_id_;
  // @@protoc_insertion_point(copy_constructor:ctpview_trader.ClearDiagnosticEvent)
}

inline void ClearDiagnosticEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.diagnostic_event_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ClearDiagnosticEvent::~ClearDiagnosticEvent() {
  // @@protoc_insertion_point(destructor:ctpview_trader.ClearDiagnosticEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ClearDiagnosticEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ClearDiagnosticEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ClearDiagnosticEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:ctpview_trader.ClearDiagnosticEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.diagnostic_event_id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClearDiagnosticEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 diagnostic_event_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.diagnostic_event_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ClearDiagnosticEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ctpview_trader.ClearDiagnosticEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 diagnostic_event_id = 1;
  if (this->_internal_diagnostic_event_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_diagnostic_event_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ctpview_trader.ClearDiagnosticEvent)
  return target;
}

size_t ClearDiagnosticEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ctpview_trader.ClearDiagnosticEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 diagnostic_event_id = 1;
  if (this->_internal_diagnostic_event_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_diagnostic_event_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ClearDiagnosticEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ClearDiagnosticEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ClearDiagnosticEvent::GetClassData() const { return &_class_data_; }


void ClearDiagnosticEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ClearDiagnosticEvent*>(&to_msg);
  auto& from = static_cast<const ClearDiagnosticEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ctpview_trader.ClearDiagnosticEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_diagnostic_event_id() != 0) {
    _this->_internal_set_diagnostic_event_id(from._internal_diagnostic_event_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ClearDiagnosticEvent::CopyFrom(const ClearDiagnosticEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ctpview_trader.ClearDiagnosticEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClearDiagnosticEvent::IsInitialized() const {
  return true;
}

void ClearDiagnosticEvent::InternalSwap(ClearDiagnosticEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.diagnostic_event_id_, other->_impl_.diagnostic_event_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ClearDiagnosticEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ctpview_2dtrader_2eproto_getter, &descriptor_table_ctpview_2dtrader_2eproto_once,
      file_level_metadata_ctpview_2dtrader_2eproto[5]);
}

// ===================================================================

class SendTestEmail::_Internal {
 public:
};

SendTestEmail::SendTestEmail(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ctpview_trader.SendTestEmail)
}
SendTestEmail::SendTestEmail(const SendTestEmail& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SendTestEmail* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.send_action_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.send_action_ = from._impl_.send_action_;
  // @@protoc_insertion_point(copy_constructor:ctpview_trader.SendTestEmail)
}

inline void SendTestEmail::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.send_action_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SendTestEmail::~SendTestEmail() {
  // @@protoc_insertion_point(destructor:ctpview_trader.SendTestEmail)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SendTestEmail::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SendTestEmail::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SendTestEmail::Clear() {
// @@protoc_insertion_point(message_clear_start:ctpview_trader.SendTestEmail)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.send_action_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendTestEmail::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ctpview_trader.SendTestEmail.SendAction send_action = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_send_action(static_cast<::ctpview_trader::SendTestEmail_SendAction>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SendTestEmail::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ctpview_trader.SendTestEmail)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ctpview_trader.SendTestEmail.SendAction send_action = 1;
  if (this->_internal_send_action() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_send_action(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ctpview_trader.SendTestEmail)
  return target;
}

size_t SendTestEmail::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ctpview_trader.SendTestEmail)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ctpview_trader.SendTestEmail.SendAction send_action = 1;
  if (this->_internal_send_action() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_send_action());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendTestEmail::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SendTestEmail::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendTestEmail::GetClassData() const { return &_class_data_; }


void SendTestEmail::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SendTestEmail*>(&to_msg);
  auto& from = static_cast<const SendTestEmail&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ctpview_trader.SendTestEmail)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_send_action() != 0) {
    _this->_internal_set_send_action(from._internal_send_action());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendTestEmail::CopyFrom(const SendTestEmail& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ctpview_trader.SendTestEmail)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendTestEmail::IsInitialized() const {
  return true;
}

void SendTestEmail::InternalSwap(SendTestEmail* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.send_action_, other->_impl_.send_action_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SendTestEmail::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ctpview_2dtrader_2eproto_getter, &descriptor_table_ctpview_2dtrader_2eproto_once,
      file_level_metadata_ctpview_2dtrader_2eproto[6]);
}

// ===================================================================

class UpdateAccountGroup::_Internal {
 public:
};

UpdateAccountGroup::UpdateAccountGroup(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ctpview_trader.UpdateAccountGroup)
}
UpdateAccountGroup::UpdateAccountGroup(const UpdateAccountGroup& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpdateAccountGroup* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.account_){from._impl_.account_}
    , decltype(_impl_.group_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.group_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.group_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_group_id().empty()) {
    _this->_impl_.group_id_.Set(from._internal_group_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ctpview_trader.UpdateAccountGroup)
}

inline void UpdateAccountGroup::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.account_){arena}
    , decltype(_impl_.group_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.group_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.group_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UpdateAccountGroup::~UpdateAccountGroup() {
  // @@protoc_insertion_point(destructor:ctpview_trader.UpdateAccountGroup)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpdateAccountGroup::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.account_.~RepeatedPtrField();
  _impl_.group_id_.Destroy();
}

void UpdateAccountGroup::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpdateAccountGroup::Clear() {
// @@protoc_insertion_point(message_clear_start:ctpview_trader.UpdateAccountGroup)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_.Clear();
  _impl_.group_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateAccountGroup::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string group_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_group_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ctpview_trader.UpdateAccountGroup.group_id"));
        } else
          goto handle_unusual;
        continue;
      // repeated string account = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_account();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "ctpview_trader.UpdateAccountGroup.account"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UpdateAccountGroup::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ctpview_trader.UpdateAccountGroup)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string group_id = 1;
  if (!this->_internal_group_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_group_id().data(), static_cast<int>(this->_internal_group_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ctpview_trader.UpdateAccountGroup.group_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_group_id(), target);
  }

  // repeated string account = 2;
  for (int i = 0, n = this->_internal_account_size(); i < n; i++) {
    const auto& s = this->_internal_account(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ctpview_trader.UpdateAccountGroup.account");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ctpview_trader.UpdateAccountGroup)
  return target;
}

size_t UpdateAccountGroup::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ctpview_trader.UpdateAccountGroup)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string account = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.account_.size());
  for (int i = 0, n = _impl_.account_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.account_.Get(i));
  }

  // string group_id = 1;
  if (!this->_internal_group_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_group_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdateAccountGroup::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpdateAccountGroup::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdateAccountGroup::GetClassData() const { return &_class_data_; }


void UpdateAccountGroup::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpdateAccountGroup*>(&to_msg);
  auto& from = static_cast<const UpdateAccountGroup&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ctpview_trader.UpdateAccountGroup)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.account_.MergeFrom(from._impl_.account_);
  if (!from._internal_group_id().empty()) {
    _this->_internal_set_group_id(from._internal_group_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateAccountGroup::CopyFrom(const UpdateAccountGroup& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ctpview_trader.UpdateAccountGroup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateAccountGroup::IsInitialized() const {
  return true;
}

void UpdateAccountGroup::InternalSwap(UpdateAccountGroup* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.account_.InternalSwap(&other->_impl_.account_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.group_id_, lhs_arena,
      &other->_impl_.group_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateAccountGroup::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ctpview_2dtrader_2eproto_getter, &descriptor_table_ctpview_2dtrader_2eproto_once,
      file_level_metadata_ctpview_2dtrader_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ctpview_trader
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ctpview_trader::message*
Arena::CreateMaybeMessage< ::ctpview_trader::message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ctpview_trader::message >(arena);
}
template<> PROTOBUF_NOINLINE ::ctpview_trader::LoginControl*
Arena::CreateMaybeMessage< ::ctpview_trader::LoginControl >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ctpview_trader::LoginControl >(arena);
}
template<> PROTOBUF_NOINLINE ::ctpview_trader::BugInjection*
Arena::CreateMaybeMessage< ::ctpview_trader::BugInjection >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ctpview_trader::BugInjection >(arena);
}
template<> PROTOBUF_NOINLINE ::ctpview_trader::ProfilerControl*
Arena::CreateMaybeMessage< ::ctpview_trader::ProfilerControl >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ctpview_trader::ProfilerControl >(arena);
}
template<> PROTOBUF_NOINLINE ::ctpview_trader::UpdatePara*
Arena::CreateMaybeMessage< ::ctpview_trader::UpdatePara >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ctpview_trader::UpdatePara >(arena);
}
template<> PROTOBUF_NOINLINE ::ctpview_trader::ClearDiagnosticEvent*
Arena::CreateMaybeMessage< ::ctpview_trader::ClearDiagnosticEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ctpview_trader::ClearDiagnosticEvent >(arena);
}
template<> PROTOBUF_NOINLINE ::ctpview_trader::SendTestEmail*
Arena::CreateMaybeMessage< ::ctpview_trader::SendTestEmail >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ctpview_trader::SendTestEmail >(arena);
}
template<> PROTOBUF_NOINLINE ::ctpview_trader::UpdateAccountGroup*
Arena::CreateMaybeMessage< ::ctpview_trader::UpdateAccountGroup >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ctpview_trader::UpdateAccountGroup >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
