// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc.proto

#include "ipc.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ipc {
PROTOBUF_CONSTEXPR message::message(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.MessageType_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct messageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR messageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~messageDefaultTypeInternal() {}
  union {
    message _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 messageDefaultTypeInternal _message_default_instance_;
PROTOBUF_CONSTEXPR ItpMsg::ItpMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.user_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.address_)*/int64_t{0}
  , /*decltype(_impl_.rsp_info_)*/int64_t{0}
  , /*decltype(_impl_.session_id_)*/uint64_t{0u}
  , /*decltype(_impl_.is_last_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ItpMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ItpMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ItpMsgDefaultTypeInternal() {}
  union {
    ItpMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ItpMsgDefaultTypeInternal _ItpMsg_default_instance_;
PROTOBUF_CONSTEXPR OrderIndex::OrderIndex(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ins_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.index_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OrderIndexDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OrderIndexDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OrderIndexDefaultTypeInternal() {}
  union {
    OrderIndex _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OrderIndexDefaultTypeInternal _OrderIndex_default_instance_;
PROTOBUF_CONSTEXPR AccountStatusReq::AccountStatusReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.indication_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AccountStatusReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountStatusReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountStatusReqDefaultTypeInternal() {}
  union {
    AccountStatusReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AccountStatusReqDefaultTypeInternal _AccountStatusReq_default_instance_;
PROTOBUF_CONSTEXPR SendEmail::SendEmail(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.head_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.body_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SendEmailDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SendEmailDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SendEmailDefaultTypeInternal() {}
  union {
    SendEmail _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SendEmailDefaultTypeInternal _SendEmail_default_instance_;
PROTOBUF_CONSTEXPR UpdateCapital::UpdateCapital(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ins_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.index_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.profit_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UpdateCapitalDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateCapitalDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateCapitalDefaultTypeInternal() {}
  union {
    UpdateCapital _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateCapitalDefaultTypeInternal _UpdateCapital_default_instance_;
}  // namespace ipc
static ::_pb::Metadata file_level_metadata_ipc_2eproto[6];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ipc_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ipc_2eproto = nullptr;

const uint32_t TableStruct_ipc_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ipc::message, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::ipc::message, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::ipc::message, _impl_.MessageType_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ipc::ItpMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ipc::ItpMsg, _impl_.address_),
  PROTOBUF_FIELD_OFFSET(::ipc::ItpMsg, _impl_.rsp_info_),
  PROTOBUF_FIELD_OFFSET(::ipc::ItpMsg, _impl_.user_id_),
  PROTOBUF_FIELD_OFFSET(::ipc::ItpMsg, _impl_.session_id_),
  PROTOBUF_FIELD_OFFSET(::ipc::ItpMsg, _impl_.is_last_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ipc::OrderIndex, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ipc::OrderIndex, _impl_.ins_),
  PROTOBUF_FIELD_OFFSET(::ipc::OrderIndex, _impl_.index_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ipc::AccountStatusReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ipc::AccountStatusReq, _impl_.indication_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ipc::SendEmail, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ipc::SendEmail, _impl_.head_),
  PROTOBUF_FIELD_OFFSET(::ipc::SendEmail, _impl_.body_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ipc::UpdateCapital, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ipc::UpdateCapital, _impl_.ins_),
  PROTOBUF_FIELD_OFFSET(::ipc::UpdateCapital, _impl_.index_),
  PROTOBUF_FIELD_OFFSET(::ipc::UpdateCapital, _impl_.profit_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ipc::message)},
  { 12, -1, -1, sizeof(::ipc::ItpMsg)},
  { 23, -1, -1, sizeof(::ipc::OrderIndex)},
  { 31, -1, -1, sizeof(::ipc::AccountStatusReq)},
  { 38, -1, -1, sizeof(::ipc::SendEmail)},
  { 46, -1, -1, sizeof(::ipc::UpdateCapital)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ipc::_message_default_instance_._instance,
  &::ipc::_ItpMsg_default_instance_._instance,
  &::ipc::_OrderIndex_default_instance_._instance,
  &::ipc::_AccountStatusReq_default_instance_._instance,
  &::ipc::_SendEmail_default_instance_._instance,
  &::ipc::_UpdateCapital_default_instance_._instance,
};

const char descriptor_table_protodef_ipc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tipc.proto\022\003ipc\"\351\001\n\007message\022\036\n\007itp_msg\030"
  "\001 \001(\0132\013.ipc.ItpMsgH\000\022&\n\013order_index\030\002 \001("
  "\0132\017.ipc.OrderIndexH\000\0223\n\022account_status_r"
  "eq\030\003 \001(\0132\025.ipc.AccountStatusReqH\000\022$\n\nsen"
  "d_email\030\004 \001(\0132\016.ipc.SendEmailH\000\022,\n\016updat"
  "e_capital\030\005 \001(\0132\022.ipc.UpdateCapitalH\000B\r\n"
  "\013MessageType\"a\n\006ItpMsg\022\017\n\007address\030\001 \001(\003\022"
  "\020\n\010rsp_info\030\002 \001(\003\022\017\n\007user_id\030\003 \001(\t\022\022\n\nse"
  "ssion_id\030\004 \001(\004\022\017\n\007is_last\030\005 \001(\010\"(\n\nOrder"
  "Index\022\013\n\003ins\030\001 \001(\t\022\r\n\005index\030\002 \001(\t\"x\n\020Acc"
  "ountStatusReq\0224\n\nindication\030\001 \001(\0162 .ipc."
  "AccountStatusReq.Indication\".\n\nIndicatio"
  "n\022\013\n\007reserve\020\000\022\t\n\005start\020\001\022\010\n\004stop\020\002\"\'\n\tS"
  "endEmail\022\014\n\004head\030\001 \001(\t\022\014\n\004body\030\002 \001(\t\";\n\r"
  "UpdateCapital\022\013\n\003ins\030\001 \001(\t\022\r\n\005index\030\002 \001("
  "\t\022\016\n\006profit\030\003 \001(\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ipc_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ipc_2eproto = {
    false, false, 625, descriptor_table_protodef_ipc_2eproto,
    "ipc.proto",
    &descriptor_table_ipc_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_ipc_2eproto::offsets,
    file_level_metadata_ipc_2eproto, file_level_enum_descriptors_ipc_2eproto,
    file_level_service_descriptors_ipc_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ipc_2eproto_getter() {
  return &descriptor_table_ipc_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ipc_2eproto(&descriptor_table_ipc_2eproto);
namespace ipc {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccountStatusReq_Indication_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ipc_2eproto);
  return file_level_enum_descriptors_ipc_2eproto[0];
}
bool AccountStatusReq_Indication_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr AccountStatusReq_Indication AccountStatusReq::reserve;
constexpr AccountStatusReq_Indication AccountStatusReq::start;
constexpr AccountStatusReq_Indication AccountStatusReq::stop;
constexpr AccountStatusReq_Indication AccountStatusReq::Indication_MIN;
constexpr AccountStatusReq_Indication AccountStatusReq::Indication_MAX;
constexpr int AccountStatusReq::Indication_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class message::_Internal {
 public:
  static const ::ipc::ItpMsg& itp_msg(const message* msg);
  static const ::ipc::OrderIndex& order_index(const message* msg);
  static const ::ipc::AccountStatusReq& account_status_req(const message* msg);
  static const ::ipc::SendEmail& send_email(const message* msg);
  static const ::ipc::UpdateCapital& update_capital(const message* msg);
};

const ::ipc::ItpMsg&
message::_Internal::itp_msg(const message* msg) {
  return *msg->_impl_.MessageType_.itp_msg_;
}
const ::ipc::OrderIndex&
message::_Internal::order_index(const message* msg) {
  return *msg->_impl_.MessageType_.order_index_;
}
const ::ipc::AccountStatusReq&
message::_Internal::account_status_req(const message* msg) {
  return *msg->_impl_.MessageType_.account_status_req_;
}
const ::ipc::SendEmail&
message::_Internal::send_email(const message* msg) {
  return *msg->_impl_.MessageType_.send_email_;
}
const ::ipc::UpdateCapital&
message::_Internal::update_capital(const message* msg) {
  return *msg->_impl_.MessageType_.update_capital_;
}
void message::set_allocated_itp_msg(::ipc::ItpMsg* itp_msg) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (itp_msg) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(itp_msg);
    if (message_arena != submessage_arena) {
      itp_msg = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, itp_msg, submessage_arena);
    }
    set_has_itp_msg();
    _impl_.MessageType_.itp_msg_ = itp_msg;
  }
  // @@protoc_insertion_point(field_set_allocated:ipc.message.itp_msg)
}
void message::set_allocated_order_index(::ipc::OrderIndex* order_index) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (order_index) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(order_index);
    if (message_arena != submessage_arena) {
      order_index = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, order_index, submessage_arena);
    }
    set_has_order_index();
    _impl_.MessageType_.order_index_ = order_index;
  }
  // @@protoc_insertion_point(field_set_allocated:ipc.message.order_index)
}
void message::set_allocated_account_status_req(::ipc::AccountStatusReq* account_status_req) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (account_status_req) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(account_status_req);
    if (message_arena != submessage_arena) {
      account_status_req = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, account_status_req, submessage_arena);
    }
    set_has_account_status_req();
    _impl_.MessageType_.account_status_req_ = account_status_req;
  }
  // @@protoc_insertion_point(field_set_allocated:ipc.message.account_status_req)
}
void message::set_allocated_send_email(::ipc::SendEmail* send_email) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (send_email) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(send_email);
    if (message_arena != submessage_arena) {
      send_email = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, send_email, submessage_arena);
    }
    set_has_send_email();
    _impl_.MessageType_.send_email_ = send_email;
  }
  // @@protoc_insertion_point(field_set_allocated:ipc.message.send_email)
}
void message::set_allocated_update_capital(::ipc::UpdateCapital* update_capital) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (update_capital) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(update_capital);
    if (message_arena != submessage_arena) {
      update_capital = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, update_capital, submessage_arena);
    }
    set_has_update_capital();
    _impl_.MessageType_.update_capital_ = update_capital;
  }
  // @@protoc_insertion_point(field_set_allocated:ipc.message.update_capital)
}
message::message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ipc.message)
}
message::message(const message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  message* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.MessageType_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_MessageType();
  switch (from.MessageType_case()) {
    case kItpMsg: {
      _this->_internal_mutable_itp_msg()->::ipc::ItpMsg::MergeFrom(
          from._internal_itp_msg());
      break;
    }
    case kOrderIndex: {
      _this->_internal_mutable_order_index()->::ipc::OrderIndex::MergeFrom(
          from._internal_order_index());
      break;
    }
    case kAccountStatusReq: {
      _this->_internal_mutable_account_status_req()->::ipc::AccountStatusReq::MergeFrom(
          from._internal_account_status_req());
      break;
    }
    case kSendEmail: {
      _this->_internal_mutable_send_email()->::ipc::SendEmail::MergeFrom(
          from._internal_send_email());
      break;
    }
    case kUpdateCapital: {
      _this->_internal_mutable_update_capital()->::ipc::UpdateCapital::MergeFrom(
          from._internal_update_capital());
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:ipc.message)
}

inline void message::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.MessageType_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_MessageType();
}

message::~message() {
  // @@protoc_insertion_point(destructor:ipc.message)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void message::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_MessageType()) {
    clear_MessageType();
  }
}

void message::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void message::clear_MessageType() {
// @@protoc_insertion_point(one_of_clear_start:ipc.message)
  switch (MessageType_case()) {
    case kItpMsg: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.itp_msg_;
      }
      break;
    }
    case kOrderIndex: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.order_index_;
      }
      break;
    }
    case kAccountStatusReq: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.account_status_req_;
      }
      break;
    }
    case kSendEmail: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.send_email_;
      }
      break;
    }
    case kUpdateCapital: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.update_capital_;
      }
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = MESSAGETYPE_NOT_SET;
}


void message::Clear() {
// @@protoc_insertion_point(message_clear_start:ipc.message)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_MessageType();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* message::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ipc.ItpMsg itp_msg = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_itp_msg(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ipc.OrderIndex order_index = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_order_index(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ipc.AccountStatusReq account_status_req = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_account_status_req(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ipc.SendEmail send_email = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_send_email(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ipc.UpdateCapital update_capital = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_update_capital(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* message::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ipc.message)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ipc.ItpMsg itp_msg = 1;
  if (_internal_has_itp_msg()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::itp_msg(this),
        _Internal::itp_msg(this).GetCachedSize(), target, stream);
  }

  // .ipc.OrderIndex order_index = 2;
  if (_internal_has_order_index()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::order_index(this),
        _Internal::order_index(this).GetCachedSize(), target, stream);
  }

  // .ipc.AccountStatusReq account_status_req = 3;
  if (_internal_has_account_status_req()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::account_status_req(this),
        _Internal::account_status_req(this).GetCachedSize(), target, stream);
  }

  // .ipc.SendEmail send_email = 4;
  if (_internal_has_send_email()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::send_email(this),
        _Internal::send_email(this).GetCachedSize(), target, stream);
  }

  // .ipc.UpdateCapital update_capital = 5;
  if (_internal_has_update_capital()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::update_capital(this),
        _Internal::update_capital(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ipc.message)
  return target;
}

size_t message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ipc.message)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (MessageType_case()) {
    // .ipc.ItpMsg itp_msg = 1;
    case kItpMsg: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.itp_msg_);
      break;
    }
    // .ipc.OrderIndex order_index = 2;
    case kOrderIndex: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.order_index_);
      break;
    }
    // .ipc.AccountStatusReq account_status_req = 3;
    case kAccountStatusReq: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.account_status_req_);
      break;
    }
    // .ipc.SendEmail send_email = 4;
    case kSendEmail: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.send_email_);
      break;
    }
    // .ipc.UpdateCapital update_capital = 5;
    case kUpdateCapital: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.update_capital_);
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData message::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    message::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*message::GetClassData() const { return &_class_data_; }


void message::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<message*>(&to_msg);
  auto& from = static_cast<const message&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ipc.message)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.MessageType_case()) {
    case kItpMsg: {
      _this->_internal_mutable_itp_msg()->::ipc::ItpMsg::MergeFrom(
          from._internal_itp_msg());
      break;
    }
    case kOrderIndex: {
      _this->_internal_mutable_order_index()->::ipc::OrderIndex::MergeFrom(
          from._internal_order_index());
      break;
    }
    case kAccountStatusReq: {
      _this->_internal_mutable_account_status_req()->::ipc::AccountStatusReq::MergeFrom(
          from._internal_account_status_req());
      break;
    }
    case kSendEmail: {
      _this->_internal_mutable_send_email()->::ipc::SendEmail::MergeFrom(
          from._internal_send_email());
      break;
    }
    case kUpdateCapital: {
      _this->_internal_mutable_update_capital()->::ipc::UpdateCapital::MergeFrom(
          from._internal_update_capital());
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void message::CopyFrom(const message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ipc.message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool message::IsInitialized() const {
  return true;
}

void message::InternalSwap(message* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.MessageType_, other->_impl_.MessageType_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata message::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2eproto_getter, &descriptor_table_ipc_2eproto_once,
      file_level_metadata_ipc_2eproto[0]);
}

// ===================================================================

class ItpMsg::_Internal {
 public:
};

ItpMsg::ItpMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ipc.ItpMsg)
}
ItpMsg::ItpMsg(const ItpMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ItpMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.user_id_){}
    , decltype(_impl_.address_){}
    , decltype(_impl_.rsp_info_){}
    , decltype(_impl_.session_id_){}
    , decltype(_impl_.is_last_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.user_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_user_id().empty()) {
    _this->_impl_.user_id_.Set(from._internal_user_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.address_, &from._impl_.address_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_last_) -
    reinterpret_cast<char*>(&_impl_.address_)) + sizeof(_impl_.is_last_));
  // @@protoc_insertion_point(copy_constructor:ipc.ItpMsg)
}

inline void ItpMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.user_id_){}
    , decltype(_impl_.address_){int64_t{0}}
    , decltype(_impl_.rsp_info_){int64_t{0}}
    , decltype(_impl_.session_id_){uint64_t{0u}}
    , decltype(_impl_.is_last_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.user_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ItpMsg::~ItpMsg() {
  // @@protoc_insertion_point(destructor:ipc.ItpMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ItpMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.user_id_.Destroy();
}

void ItpMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ItpMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:ipc.ItpMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  ::memset(&_impl_.address_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_last_) -
      reinterpret_cast<char*>(&_impl_.address_)) + sizeof(_impl_.is_last_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ItpMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 address = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.address_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 rsp_info = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.rsp_info_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string user_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_user_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipc.ItpMsg.user_id"));
        } else
          goto handle_unusual;
        continue;
      // uint64 session_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_last = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.is_last_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ItpMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ipc.ItpMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 address = 1;
  if (this->_internal_address() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_address(), target);
  }

  // int64 rsp_info = 2;
  if (this->_internal_rsp_info() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_rsp_info(), target);
  }

  // string user_id = 3;
  if (!this->_internal_user_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_user_id().data(), static_cast<int>(this->_internal_user_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipc.ItpMsg.user_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_user_id(), target);
  }

  // uint64 session_id = 4;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_session_id(), target);
  }

  // bool is_last = 5;
  if (this->_internal_is_last() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_is_last(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ipc.ItpMsg)
  return target;
}

size_t ItpMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ipc.ItpMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string user_id = 3;
  if (!this->_internal_user_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_user_id());
  }

  // int64 address = 1;
  if (this->_internal_address() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_address());
  }

  // int64 rsp_info = 2;
  if (this->_internal_rsp_info() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_rsp_info());
  }

  // uint64 session_id = 4;
  if (this->_internal_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_session_id());
  }

  // bool is_last = 5;
  if (this->_internal_is_last() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ItpMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ItpMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ItpMsg::GetClassData() const { return &_class_data_; }


void ItpMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ItpMsg*>(&to_msg);
  auto& from = static_cast<const ItpMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ipc.ItpMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_address() != 0) {
    _this->_internal_set_address(from._internal_address());
  }
  if (from._internal_rsp_info() != 0) {
    _this->_internal_set_rsp_info(from._internal_rsp_info());
  }
  if (from._internal_session_id() != 0) {
    _this->_internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_is_last() != 0) {
    _this->_internal_set_is_last(from._internal_is_last());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ItpMsg::CopyFrom(const ItpMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ipc.ItpMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItpMsg::IsInitialized() const {
  return true;
}

void ItpMsg::InternalSwap(ItpMsg* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.user_id_, lhs_arena,
      &other->_impl_.user_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ItpMsg, _impl_.is_last_)
      + sizeof(ItpMsg::_impl_.is_last_)
      - PROTOBUF_FIELD_OFFSET(ItpMsg, _impl_.address_)>(
          reinterpret_cast<char*>(&_impl_.address_),
          reinterpret_cast<char*>(&other->_impl_.address_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ItpMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2eproto_getter, &descriptor_table_ipc_2eproto_once,
      file_level_metadata_ipc_2eproto[1]);
}

// ===================================================================

class OrderIndex::_Internal {
 public:
};

OrderIndex::OrderIndex(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ipc.OrderIndex)
}
OrderIndex::OrderIndex(const OrderIndex& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OrderIndex* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ins_){}
    , decltype(_impl_.index_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ins_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ins_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ins().empty()) {
    _this->_impl_.ins_.Set(from._internal_ins(), 
      _this->GetArenaForAllocation());
  }
  _impl_.index_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.index_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_index().empty()) {
    _this->_impl_.index_.Set(from._internal_index(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ipc.OrderIndex)
}

inline void OrderIndex::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ins_){}
    , decltype(_impl_.index_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.ins_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ins_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.index_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.index_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OrderIndex::~OrderIndex() {
  // @@protoc_insertion_point(destructor:ipc.OrderIndex)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OrderIndex::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ins_.Destroy();
  _impl_.index_.Destroy();
}

void OrderIndex::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OrderIndex::Clear() {
// @@protoc_insertion_point(message_clear_start:ipc.OrderIndex)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ins_.ClearToEmpty();
  _impl_.index_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OrderIndex::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string ins = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_ins();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipc.OrderIndex.ins"));
        } else
          goto handle_unusual;
        continue;
      // string index = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_index();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipc.OrderIndex.index"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OrderIndex::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ipc.OrderIndex)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string ins = 1;
  if (!this->_internal_ins().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ins().data(), static_cast<int>(this->_internal_ins().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipc.OrderIndex.ins");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ins(), target);
  }

  // string index = 2;
  if (!this->_internal_index().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_index().data(), static_cast<int>(this->_internal_index().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipc.OrderIndex.index");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_index(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ipc.OrderIndex)
  return target;
}

size_t OrderIndex::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ipc.OrderIndex)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ins = 1;
  if (!this->_internal_ins().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ins());
  }

  // string index = 2;
  if (!this->_internal_index().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_index());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OrderIndex::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OrderIndex::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OrderIndex::GetClassData() const { return &_class_data_; }


void OrderIndex::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OrderIndex*>(&to_msg);
  auto& from = static_cast<const OrderIndex&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ipc.OrderIndex)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ins().empty()) {
    _this->_internal_set_ins(from._internal_ins());
  }
  if (!from._internal_index().empty()) {
    _this->_internal_set_index(from._internal_index());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OrderIndex::CopyFrom(const OrderIndex& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ipc.OrderIndex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OrderIndex::IsInitialized() const {
  return true;
}

void OrderIndex::InternalSwap(OrderIndex* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ins_, lhs_arena,
      &other->_impl_.ins_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.index_, lhs_arena,
      &other->_impl_.index_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata OrderIndex::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2eproto_getter, &descriptor_table_ipc_2eproto_once,
      file_level_metadata_ipc_2eproto[2]);
}

// ===================================================================

class AccountStatusReq::_Internal {
 public:
};

AccountStatusReq::AccountStatusReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ipc.AccountStatusReq)
}
AccountStatusReq::AccountStatusReq(const AccountStatusReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AccountStatusReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.indication_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.indication_ = from._impl_.indication_;
  // @@protoc_insertion_point(copy_constructor:ipc.AccountStatusReq)
}

inline void AccountStatusReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.indication_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AccountStatusReq::~AccountStatusReq() {
  // @@protoc_insertion_point(destructor:ipc.AccountStatusReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AccountStatusReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void AccountStatusReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AccountStatusReq::Clear() {
// @@protoc_insertion_point(message_clear_start:ipc.AccountStatusReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.indication_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AccountStatusReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ipc.AccountStatusReq.Indication indication = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_indication(static_cast<::ipc::AccountStatusReq_Indication>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AccountStatusReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ipc.AccountStatusReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ipc.AccountStatusReq.Indication indication = 1;
  if (this->_internal_indication() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_indication(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ipc.AccountStatusReq)
  return target;
}

size_t AccountStatusReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ipc.AccountStatusReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ipc.AccountStatusReq.Indication indication = 1;
  if (this->_internal_indication() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_indication());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AccountStatusReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AccountStatusReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AccountStatusReq::GetClassData() const { return &_class_data_; }


void AccountStatusReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AccountStatusReq*>(&to_msg);
  auto& from = static_cast<const AccountStatusReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ipc.AccountStatusReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_indication() != 0) {
    _this->_internal_set_indication(from._internal_indication());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AccountStatusReq::CopyFrom(const AccountStatusReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ipc.AccountStatusReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccountStatusReq::IsInitialized() const {
  return true;
}

void AccountStatusReq::InternalSwap(AccountStatusReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.indication_, other->_impl_.indication_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AccountStatusReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2eproto_getter, &descriptor_table_ipc_2eproto_once,
      file_level_metadata_ipc_2eproto[3]);
}

// ===================================================================

class SendEmail::_Internal {
 public:
};

SendEmail::SendEmail(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ipc.SendEmail)
}
SendEmail::SendEmail(const SendEmail& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SendEmail* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.head_){}
    , decltype(_impl_.body_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.head_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.head_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_head().empty()) {
    _this->_impl_.head_.Set(from._internal_head(), 
      _this->GetArenaForAllocation());
  }
  _impl_.body_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.body_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_body().empty()) {
    _this->_impl_.body_.Set(from._internal_body(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ipc.SendEmail)
}

inline void SendEmail::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.head_){}
    , decltype(_impl_.body_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.head_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.head_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.body_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.body_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SendEmail::~SendEmail() {
  // @@protoc_insertion_point(destructor:ipc.SendEmail)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SendEmail::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.head_.Destroy();
  _impl_.body_.Destroy();
}

void SendEmail::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SendEmail::Clear() {
// @@protoc_insertion_point(message_clear_start:ipc.SendEmail)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.head_.ClearToEmpty();
  _impl_.body_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendEmail::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string head = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_head();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipc.SendEmail.head"));
        } else
          goto handle_unusual;
        continue;
      // string body = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_body();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipc.SendEmail.body"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SendEmail::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ipc.SendEmail)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string head = 1;
  if (!this->_internal_head().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_head().data(), static_cast<int>(this->_internal_head().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipc.SendEmail.head");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_head(), target);
  }

  // string body = 2;
  if (!this->_internal_body().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_body().data(), static_cast<int>(this->_internal_body().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipc.SendEmail.body");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_body(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ipc.SendEmail)
  return target;
}

size_t SendEmail::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ipc.SendEmail)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string head = 1;
  if (!this->_internal_head().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_head());
  }

  // string body = 2;
  if (!this->_internal_body().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_body());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendEmail::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SendEmail::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendEmail::GetClassData() const { return &_class_data_; }


void SendEmail::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SendEmail*>(&to_msg);
  auto& from = static_cast<const SendEmail&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ipc.SendEmail)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_head().empty()) {
    _this->_internal_set_head(from._internal_head());
  }
  if (!from._internal_body().empty()) {
    _this->_internal_set_body(from._internal_body());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendEmail::CopyFrom(const SendEmail& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ipc.SendEmail)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendEmail::IsInitialized() const {
  return true;
}

void SendEmail::InternalSwap(SendEmail* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.head_, lhs_arena,
      &other->_impl_.head_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.body_, lhs_arena,
      &other->_impl_.body_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SendEmail::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2eproto_getter, &descriptor_table_ipc_2eproto_once,
      file_level_metadata_ipc_2eproto[4]);
}

// ===================================================================

class UpdateCapital::_Internal {
 public:
};

UpdateCapital::UpdateCapital(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ipc.UpdateCapital)
}
UpdateCapital::UpdateCapital(const UpdateCapital& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpdateCapital* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ins_){}
    , decltype(_impl_.index_){}
    , decltype(_impl_.profit_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ins_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ins_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ins().empty()) {
    _this->_impl_.ins_.Set(from._internal_ins(), 
      _this->GetArenaForAllocation());
  }
  _impl_.index_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.index_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_index().empty()) {
    _this->_impl_.index_.Set(from._internal_index(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.profit_ = from._impl_.profit_;
  // @@protoc_insertion_point(copy_constructor:ipc.UpdateCapital)
}

inline void UpdateCapital::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ins_){}
    , decltype(_impl_.index_){}
    , decltype(_impl_.profit_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.ins_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ins_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.index_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.index_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UpdateCapital::~UpdateCapital() {
  // @@protoc_insertion_point(destructor:ipc.UpdateCapital)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpdateCapital::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ins_.Destroy();
  _impl_.index_.Destroy();
}

void UpdateCapital::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpdateCapital::Clear() {
// @@protoc_insertion_point(message_clear_start:ipc.UpdateCapital)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ins_.ClearToEmpty();
  _impl_.index_.ClearToEmpty();
  _impl_.profit_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateCapital::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string ins = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_ins();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipc.UpdateCapital.ins"));
        } else
          goto handle_unusual;
        continue;
      // string index = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_index();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipc.UpdateCapital.index"));
        } else
          goto handle_unusual;
        continue;
      // double profit = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.profit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UpdateCapital::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ipc.UpdateCapital)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string ins = 1;
  if (!this->_internal_ins().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ins().data(), static_cast<int>(this->_internal_ins().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipc.UpdateCapital.ins");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ins(), target);
  }

  // string index = 2;
  if (!this->_internal_index().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_index().data(), static_cast<int>(this->_internal_index().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipc.UpdateCapital.index");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_index(), target);
  }

  // double profit = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_profit = this->_internal_profit();
  uint64_t raw_profit;
  memcpy(&raw_profit, &tmp_profit, sizeof(tmp_profit));
  if (raw_profit != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_profit(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ipc.UpdateCapital)
  return target;
}

size_t UpdateCapital::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ipc.UpdateCapital)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ins = 1;
  if (!this->_internal_ins().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ins());
  }

  // string index = 2;
  if (!this->_internal_index().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_index());
  }

  // double profit = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_profit = this->_internal_profit();
  uint64_t raw_profit;
  memcpy(&raw_profit, &tmp_profit, sizeof(tmp_profit));
  if (raw_profit != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdateCapital::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpdateCapital::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdateCapital::GetClassData() const { return &_class_data_; }


void UpdateCapital::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpdateCapital*>(&to_msg);
  auto& from = static_cast<const UpdateCapital&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ipc.UpdateCapital)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ins().empty()) {
    _this->_internal_set_ins(from._internal_ins());
  }
  if (!from._internal_index().empty()) {
    _this->_internal_set_index(from._internal_index());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_profit = from._internal_profit();
  uint64_t raw_profit;
  memcpy(&raw_profit, &tmp_profit, sizeof(tmp_profit));
  if (raw_profit != 0) {
    _this->_internal_set_profit(from._internal_profit());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateCapital::CopyFrom(const UpdateCapital& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ipc.UpdateCapital)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateCapital::IsInitialized() const {
  return true;
}

void UpdateCapital::InternalSwap(UpdateCapital* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ins_, lhs_arena,
      &other->_impl_.ins_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.index_, lhs_arena,
      &other->_impl_.index_, rhs_arena
  );
  swap(_impl_.profit_, other->_impl_.profit_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateCapital::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2eproto_getter, &descriptor_table_ipc_2eproto_once,
      file_level_metadata_ipc_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ipc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ipc::message*
Arena::CreateMaybeMessage< ::ipc::message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ipc::message >(arena);
}
template<> PROTOBUF_NOINLINE ::ipc::ItpMsg*
Arena::CreateMaybeMessage< ::ipc::ItpMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ipc::ItpMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::ipc::OrderIndex*
Arena::CreateMaybeMessage< ::ipc::OrderIndex >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ipc::OrderIndex >(arena);
}
template<> PROTOBUF_NOINLINE ::ipc::AccountStatusReq*
Arena::CreateMaybeMessage< ::ipc::AccountStatusReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ipc::AccountStatusReq >(arena);
}
template<> PROTOBUF_NOINLINE ::ipc::SendEmail*
Arena::CreateMaybeMessage< ::ipc::SendEmail >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ipc::SendEmail >(arena);
}
template<> PROTOBUF_NOINLINE ::ipc::UpdateCapital*
Arena::CreateMaybeMessage< ::ipc::UpdateCapital >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ipc::UpdateCapital >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
