// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: market-trader.proto

#include "market-trader.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace market_trader {
PROTOBUF_CONSTEXPR message::message(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.MessageType_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct messageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR messageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~messageDefaultTypeInternal() {}
  union {
    message _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 messageDefaultTypeInternal _message_default_instance_;
PROTOBUF_CONSTEXPR QryInstrumentRsp::QryInstrumentRsp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.instrument_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.exchange_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.result_)*/0
  , /*decltype(_impl_.finish_flag_)*/false
  , /*decltype(_impl_.is_trade_)*/false
  , /*decltype(_impl_.ticksize_)*/0
  , /*decltype(_impl_.tradeuint_)*/0
  , /*decltype(_impl_.min_limit_volume_)*/0u
  , /*decltype(_impl_.max_limit_volume_)*/0u
  , /*decltype(_impl_.min_market_volume_)*/0u
  , /*decltype(_impl_.max_market_volume_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct QryInstrumentRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QryInstrumentRspDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~QryInstrumentRspDefaultTypeInternal() {}
  union {
    QryInstrumentRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QryInstrumentRspDefaultTypeInternal _QryInstrumentRsp_default_instance_;
PROTOBUF_CONSTEXPR QryInstrumentReq::QryInstrumentReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.identity_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct QryInstrumentReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QryInstrumentReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~QryInstrumentReqDefaultTypeInternal() {}
  union {
    QryInstrumentReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QryInstrumentReqDefaultTypeInternal _QryInstrumentReq_default_instance_;
PROTOBUF_CONSTEXPR ActiveInstrumentRsp::ActiveInstrumentRsp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.instrumens_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.exchangeid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.bislast_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ActiveInstrumentRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActiveInstrumentRspDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActiveInstrumentRspDefaultTypeInternal() {}
  union {
    ActiveInstrumentRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActiveInstrumentRspDefaultTypeInternal _ActiveInstrumentRsp_default_instance_;
PROTOBUF_CONSTEXPR ActiveInstrumentReq::ActiveInstrumentReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.instrument_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ActiveInstrumentReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActiveInstrumentReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActiveInstrumentReqDefaultTypeInternal() {}
  union {
    ActiveInstrumentReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActiveInstrumentReqDefaultTypeInternal _ActiveInstrumentReq_default_instance_;
PROTOBUF_CONSTEXPR MarketStateReq::MarketStateReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.date_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.market_state_)*/0
  , /*decltype(_impl_.is_last_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MarketStateReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MarketStateReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MarketStateReqDefaultTypeInternal() {}
  union {
    MarketStateReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MarketStateReqDefaultTypeInternal _MarketStateReq_default_instance_;
PROTOBUF_CONSTEXPR MarketStateRsp::MarketStateRsp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MarketStateRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MarketStateRspDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MarketStateRspDefaultTypeInternal() {}
  union {
    MarketStateRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MarketStateRspDefaultTypeInternal _MarketStateRsp_default_instance_;
}  // namespace market_trader
static ::_pb::Metadata file_level_metadata_market_2dtrader_2eproto[7];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_market_2dtrader_2eproto[3];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_market_2dtrader_2eproto = nullptr;

const uint32_t TableStruct_market_2dtrader_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::market_trader::message, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::market_trader::message, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::market_trader::message, _impl_.MessageType_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.result_),
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.finish_flag_),
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.instrument_id_),
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.exchange_id_),
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.ticksize_),
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.tradeuint_),
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.min_limit_volume_),
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.max_limit_volume_),
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.min_market_volume_),
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.max_market_volume_),
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentRsp, _impl_.is_trade_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::market_trader::QryInstrumentReq, _impl_.identity_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::market_trader::ActiveInstrumentRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::market_trader::ActiveInstrumentRsp, _impl_.instrumens_),
  PROTOBUF_FIELD_OFFSET(::market_trader::ActiveInstrumentRsp, _impl_.exchangeid_),
  PROTOBUF_FIELD_OFFSET(::market_trader::ActiveInstrumentRsp, _impl_.bislast_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::market_trader::ActiveInstrumentReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::market_trader::ActiveInstrumentReq, _impl_.instrument_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::market_trader::MarketStateReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::market_trader::MarketStateReq, _impl_.market_state_),
  PROTOBUF_FIELD_OFFSET(::market_trader::MarketStateReq, _impl_.date_),
  PROTOBUF_FIELD_OFFSET(::market_trader::MarketStateReq, _impl_.is_last_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::market_trader::MarketStateRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::market_trader::MarketStateRsp, _impl_.result_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::market_trader::message)},
  { 13, -1, -1, sizeof(::market_trader::QryInstrumentRsp)},
  { 30, -1, -1, sizeof(::market_trader::QryInstrumentReq)},
  { 37, -1, -1, sizeof(::market_trader::ActiveInstrumentRsp)},
  { 46, -1, -1, sizeof(::market_trader::ActiveInstrumentReq)},
  { 53, -1, -1, sizeof(::market_trader::MarketStateReq)},
  { 62, -1, -1, sizeof(::market_trader::MarketStateRsp)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::market_trader::_message_default_instance_._instance,
  &::market_trader::_QryInstrumentRsp_default_instance_._instance,
  &::market_trader::_QryInstrumentReq_default_instance_._instance,
  &::market_trader::_ActiveInstrumentRsp_default_instance_._instance,
  &::market_trader::_ActiveInstrumentReq_default_instance_._instance,
  &::market_trader::_MarketStateReq_default_instance_._instance,
  &::market_trader::_MarketStateRsp_default_instance_._instance,
};

const char descriptor_table_protodef_market_2dtrader_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023market-trader.proto\022\rmarket_trader\"\226\003\n"
  "\007message\022C\n\025active_instrument_req\030\001 \001(\0132"
  "\".market_trader.ActiveInstrumentReqH\000\022C\n"
  "\025active_instrument_rsp\030\002 \001(\0132\".market_tr"
  "ader.ActiveInstrumentRspH\000\022=\n\022qry_instru"
  "ment_req\030\003 \001(\0132\037.market_trader.QryInstru"
  "mentReqH\000\022=\n\022qry_instrument_rsp\030\004 \001(\0132\037."
  "market_trader.QryInstrumentRspH\000\0229\n\020mark"
  "et_state_req\030\005 \001(\0132\035.market_trader.Marke"
  "tStateReqH\000\0229\n\020market_state_rsp\030\006 \001(\0132\035."
  "market_trader.MarketStateRspH\000B\r\n\013Messag"
  "eType\"\233\002\n\020QryInstrumentRsp\022%\n\006result\030\001 \001"
  "(\0162\025.market_trader.Result\022\023\n\013finish_flag"
  "\030\002 \001(\010\022\025\n\rinstrument_id\030\003 \001(\t\022\023\n\013exchang"
  "e_id\030\004 \001(\t\022\020\n\010ticksize\030\005 \001(\001\022\021\n\ttradeuin"
  "t\030\006 \001(\001\022\030\n\020min_limit_volume\030\007 \001(\r\022\030\n\020max"
  "_limit_volume\030\010 \001(\r\022\031\n\021min_market_volume"
  "\030\t \001(\r\022\031\n\021max_market_volume\030\n \001(\r\022\020\n\010is_"
  "trade\030\013 \001(\010\"$\n\020QryInstrumentReq\022\020\n\010ident"
  "ity\030\001 \001(\t\"N\n\023ActiveInstrumentRsp\022\022\n\ninst"
  "rumens\030\001 \001(\t\022\022\n\nExchangeID\030\002 \001(\t\022\017\n\007bIsL"
  "ast\030\003 \001(\r\"\257\001\n\023ActiveInstrumentReq\022J\n\017ins"
  "trument_type\030\001 \001(\01621.market_trader.Activ"
  "eInstrumentReq.InstrumentType\"L\n\016Instrum"
  "entType\022\013\n\007reserve\020\000\022\013\n\007futures\020\001\022\013\n\007opt"
  "ions\020\002\022\023\n\017futures_options\020\003\"\312\001\n\016MarketSt"
  "ateReq\022\?\n\014market_state\030\001 \001(\0162).market_tr"
  "ader.MarketStateReq.MarketState\022\014\n\004date\030"
  "\002 \001(\t\022\017\n\007is_last\030\003 \001(\010\"X\n\013MarketState\022\013\n"
  "\007reserve\020\000\022\014\n\010day_open\020\001\022\r\n\tday_close\020\002\022"
  "\016\n\nnight_open\020\003\022\017\n\013night_close\020\004\" \n\016Mark"
  "etStateRsp\022\016\n\006result\030\001 \001(\r*5\n\006Result\022\022\n\016"
  "Result_INVALID\020\000\022\013\n\007success\020\001\022\n\n\006failed\020"
  "\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_market_2dtrader_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_market_2dtrader_2eproto = {
    false, false, 1329, descriptor_table_protodef_market_2dtrader_2eproto,
    "market-trader.proto",
    &descriptor_table_market_2dtrader_2eproto_once, nullptr, 0, 7,
    schemas, file_default_instances, TableStruct_market_2dtrader_2eproto::offsets,
    file_level_metadata_market_2dtrader_2eproto, file_level_enum_descriptors_market_2dtrader_2eproto,
    file_level_service_descriptors_market_2dtrader_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_market_2dtrader_2eproto_getter() {
  return &descriptor_table_market_2dtrader_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_market_2dtrader_2eproto(&descriptor_table_market_2dtrader_2eproto);
namespace market_trader {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ActiveInstrumentReq_InstrumentType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_market_2dtrader_2eproto);
  return file_level_enum_descriptors_market_2dtrader_2eproto[0];
}
bool ActiveInstrumentReq_InstrumentType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr ActiveInstrumentReq_InstrumentType ActiveInstrumentReq::reserve;
constexpr ActiveInstrumentReq_InstrumentType ActiveInstrumentReq::futures;
constexpr ActiveInstrumentReq_InstrumentType ActiveInstrumentReq::options;
constexpr ActiveInstrumentReq_InstrumentType ActiveInstrumentReq::futures_options;
constexpr ActiveInstrumentReq_InstrumentType ActiveInstrumentReq::InstrumentType_MIN;
constexpr ActiveInstrumentReq_InstrumentType ActiveInstrumentReq::InstrumentType_MAX;
constexpr int ActiveInstrumentReq::InstrumentType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MarketStateReq_MarketState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_market_2dtrader_2eproto);
  return file_level_enum_descriptors_market_2dtrader_2eproto[1];
}
bool MarketStateReq_MarketState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr MarketStateReq_MarketState MarketStateReq::reserve;
constexpr MarketStateReq_MarketState MarketStateReq::day_open;
constexpr MarketStateReq_MarketState MarketStateReq::day_close;
constexpr MarketStateReq_MarketState MarketStateReq::night_open;
constexpr MarketStateReq_MarketState MarketStateReq::night_close;
constexpr MarketStateReq_MarketState MarketStateReq::MarketState_MIN;
constexpr MarketStateReq_MarketState MarketStateReq::MarketState_MAX;
constexpr int MarketStateReq::MarketState_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Result_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_market_2dtrader_2eproto);
  return file_level_enum_descriptors_market_2dtrader_2eproto[2];
}
bool Result_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class message::_Internal {
 public:
  static const ::market_trader::ActiveInstrumentReq& active_instrument_req(const message* msg);
  static const ::market_trader::ActiveInstrumentRsp& active_instrument_rsp(const message* msg);
  static const ::market_trader::QryInstrumentReq& qry_instrument_req(const message* msg);
  static const ::market_trader::QryInstrumentRsp& qry_instrument_rsp(const message* msg);
  static const ::market_trader::MarketStateReq& market_state_req(const message* msg);
  static const ::market_trader::MarketStateRsp& market_state_rsp(const message* msg);
};

const ::market_trader::ActiveInstrumentReq&
message::_Internal::active_instrument_req(const message* msg) {
  return *msg->_impl_.MessageType_.active_instrument_req_;
}
const ::market_trader::ActiveInstrumentRsp&
message::_Internal::active_instrument_rsp(const message* msg) {
  return *msg->_impl_.MessageType_.active_instrument_rsp_;
}
const ::market_trader::QryInstrumentReq&
message::_Internal::qry_instrument_req(const message* msg) {
  return *msg->_impl_.MessageType_.qry_instrument_req_;
}
const ::market_trader::QryInstrumentRsp&
message::_Internal::qry_instrument_rsp(const message* msg) {
  return *msg->_impl_.MessageType_.qry_instrument_rsp_;
}
const ::market_trader::MarketStateReq&
message::_Internal::market_state_req(const message* msg) {
  return *msg->_impl_.MessageType_.market_state_req_;
}
const ::market_trader::MarketStateRsp&
message::_Internal::market_state_rsp(const message* msg) {
  return *msg->_impl_.MessageType_.market_state_rsp_;
}
void message::set_allocated_active_instrument_req(::market_trader::ActiveInstrumentReq* active_instrument_req) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (active_instrument_req) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(active_instrument_req);
    if (message_arena != submessage_arena) {
      active_instrument_req = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, active_instrument_req, submessage_arena);
    }
    set_has_active_instrument_req();
    _impl_.MessageType_.active_instrument_req_ = active_instrument_req;
  }
  // @@protoc_insertion_point(field_set_allocated:market_trader.message.active_instrument_req)
}
void message::set_allocated_active_instrument_rsp(::market_trader::ActiveInstrumentRsp* active_instrument_rsp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (active_instrument_rsp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(active_instrument_rsp);
    if (message_arena != submessage_arena) {
      active_instrument_rsp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, active_instrument_rsp, submessage_arena);
    }
    set_has_active_instrument_rsp();
    _impl_.MessageType_.active_instrument_rsp_ = active_instrument_rsp;
  }
  // @@protoc_insertion_point(field_set_allocated:market_trader.message.active_instrument_rsp)
}
void message::set_allocated_qry_instrument_req(::market_trader::QryInstrumentReq* qry_instrument_req) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (qry_instrument_req) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(qry_instrument_req);
    if (message_arena != submessage_arena) {
      qry_instrument_req = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, qry_instrument_req, submessage_arena);
    }
    set_has_qry_instrument_req();
    _impl_.MessageType_.qry_instrument_req_ = qry_instrument_req;
  }
  // @@protoc_insertion_point(field_set_allocated:market_trader.message.qry_instrument_req)
}
void message::set_allocated_qry_instrument_rsp(::market_trader::QryInstrumentRsp* qry_instrument_rsp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (qry_instrument_rsp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(qry_instrument_rsp);
    if (message_arena != submessage_arena) {
      qry_instrument_rsp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, qry_instrument_rsp, submessage_arena);
    }
    set_has_qry_instrument_rsp();
    _impl_.MessageType_.qry_instrument_rsp_ = qry_instrument_rsp;
  }
  // @@protoc_insertion_point(field_set_allocated:market_trader.message.qry_instrument_rsp)
}
void message::set_allocated_market_state_req(::market_trader::MarketStateReq* market_state_req) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (market_state_req) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(market_state_req);
    if (message_arena != submessage_arena) {
      market_state_req = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, market_state_req, submessage_arena);
    }
    set_has_market_state_req();
    _impl_.MessageType_.market_state_req_ = market_state_req;
  }
  // @@protoc_insertion_point(field_set_allocated:market_trader.message.market_state_req)
}
void message::set_allocated_market_state_rsp(::market_trader::MarketStateRsp* market_state_rsp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_MessageType();
  if (market_state_rsp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(market_state_rsp);
    if (message_arena != submessage_arena) {
      market_state_rsp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, market_state_rsp, submessage_arena);
    }
    set_has_market_state_rsp();
    _impl_.MessageType_.market_state_rsp_ = market_state_rsp;
  }
  // @@protoc_insertion_point(field_set_allocated:market_trader.message.market_state_rsp)
}
message::message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:market_trader.message)
}
message::message(const message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  message* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.MessageType_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_MessageType();
  switch (from.MessageType_case()) {
    case kActiveInstrumentReq: {
      _this->_internal_mutable_active_instrument_req()->::market_trader::ActiveInstrumentReq::MergeFrom(
          from._internal_active_instrument_req());
      break;
    }
    case kActiveInstrumentRsp: {
      _this->_internal_mutable_active_instrument_rsp()->::market_trader::ActiveInstrumentRsp::MergeFrom(
          from._internal_active_instrument_rsp());
      break;
    }
    case kQryInstrumentReq: {
      _this->_internal_mutable_qry_instrument_req()->::market_trader::QryInstrumentReq::MergeFrom(
          from._internal_qry_instrument_req());
      break;
    }
    case kQryInstrumentRsp: {
      _this->_internal_mutable_qry_instrument_rsp()->::market_trader::QryInstrumentRsp::MergeFrom(
          from._internal_qry_instrument_rsp());
      break;
    }
    case kMarketStateReq: {
      _this->_internal_mutable_market_state_req()->::market_trader::MarketStateReq::MergeFrom(
          from._internal_market_state_req());
      break;
    }
    case kMarketStateRsp: {
      _this->_internal_mutable_market_state_rsp()->::market_trader::MarketStateRsp::MergeFrom(
          from._internal_market_state_rsp());
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:market_trader.message)
}

inline void message::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.MessageType_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_MessageType();
}

message::~message() {
  // @@protoc_insertion_point(destructor:market_trader.message)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void message::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_MessageType()) {
    clear_MessageType();
  }
}

void message::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void message::clear_MessageType() {
// @@protoc_insertion_point(one_of_clear_start:market_trader.message)
  switch (MessageType_case()) {
    case kActiveInstrumentReq: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.active_instrument_req_;
      }
      break;
    }
    case kActiveInstrumentRsp: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.active_instrument_rsp_;
      }
      break;
    }
    case kQryInstrumentReq: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.qry_instrument_req_;
      }
      break;
    }
    case kQryInstrumentRsp: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.qry_instrument_rsp_;
      }
      break;
    }
    case kMarketStateReq: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.market_state_req_;
      }
      break;
    }
    case kMarketStateRsp: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.MessageType_.market_state_rsp_;
      }
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = MESSAGETYPE_NOT_SET;
}


void message::Clear() {
// @@protoc_insertion_point(message_clear_start:market_trader.message)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_MessageType();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* message::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .market_trader.ActiveInstrumentReq active_instrument_req = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_active_instrument_req(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .market_trader.ActiveInstrumentRsp active_instrument_rsp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_active_instrument_rsp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .market_trader.QryInstrumentReq qry_instrument_req = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_qry_instrument_req(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .market_trader.QryInstrumentRsp qry_instrument_rsp = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_qry_instrument_rsp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .market_trader.MarketStateReq market_state_req = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_market_state_req(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .market_trader.MarketStateRsp market_state_rsp = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_market_state_rsp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* message::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:market_trader.message)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .market_trader.ActiveInstrumentReq active_instrument_req = 1;
  if (_internal_has_active_instrument_req()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::active_instrument_req(this),
        _Internal::active_instrument_req(this).GetCachedSize(), target, stream);
  }

  // .market_trader.ActiveInstrumentRsp active_instrument_rsp = 2;
  if (_internal_has_active_instrument_rsp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::active_instrument_rsp(this),
        _Internal::active_instrument_rsp(this).GetCachedSize(), target, stream);
  }

  // .market_trader.QryInstrumentReq qry_instrument_req = 3;
  if (_internal_has_qry_instrument_req()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::qry_instrument_req(this),
        _Internal::qry_instrument_req(this).GetCachedSize(), target, stream);
  }

  // .market_trader.QryInstrumentRsp qry_instrument_rsp = 4;
  if (_internal_has_qry_instrument_rsp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::qry_instrument_rsp(this),
        _Internal::qry_instrument_rsp(this).GetCachedSize(), target, stream);
  }

  // .market_trader.MarketStateReq market_state_req = 5;
  if (_internal_has_market_state_req()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::market_state_req(this),
        _Internal::market_state_req(this).GetCachedSize(), target, stream);
  }

  // .market_trader.MarketStateRsp market_state_rsp = 6;
  if (_internal_has_market_state_rsp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::market_state_rsp(this),
        _Internal::market_state_rsp(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:market_trader.message)
  return target;
}

size_t message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:market_trader.message)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (MessageType_case()) {
    // .market_trader.ActiveInstrumentReq active_instrument_req = 1;
    case kActiveInstrumentReq: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.active_instrument_req_);
      break;
    }
    // .market_trader.ActiveInstrumentRsp active_instrument_rsp = 2;
    case kActiveInstrumentRsp: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.active_instrument_rsp_);
      break;
    }
    // .market_trader.QryInstrumentReq qry_instrument_req = 3;
    case kQryInstrumentReq: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.qry_instrument_req_);
      break;
    }
    // .market_trader.QryInstrumentRsp qry_instrument_rsp = 4;
    case kQryInstrumentRsp: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.qry_instrument_rsp_);
      break;
    }
    // .market_trader.MarketStateReq market_state_req = 5;
    case kMarketStateReq: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.market_state_req_);
      break;
    }
    // .market_trader.MarketStateRsp market_state_rsp = 6;
    case kMarketStateRsp: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.MessageType_.market_state_rsp_);
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData message::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    message::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*message::GetClassData() const { return &_class_data_; }


void message::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<message*>(&to_msg);
  auto& from = static_cast<const message&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:market_trader.message)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.MessageType_case()) {
    case kActiveInstrumentReq: {
      _this->_internal_mutable_active_instrument_req()->::market_trader::ActiveInstrumentReq::MergeFrom(
          from._internal_active_instrument_req());
      break;
    }
    case kActiveInstrumentRsp: {
      _this->_internal_mutable_active_instrument_rsp()->::market_trader::ActiveInstrumentRsp::MergeFrom(
          from._internal_active_instrument_rsp());
      break;
    }
    case kQryInstrumentReq: {
      _this->_internal_mutable_qry_instrument_req()->::market_trader::QryInstrumentReq::MergeFrom(
          from._internal_qry_instrument_req());
      break;
    }
    case kQryInstrumentRsp: {
      _this->_internal_mutable_qry_instrument_rsp()->::market_trader::QryInstrumentRsp::MergeFrom(
          from._internal_qry_instrument_rsp());
      break;
    }
    case kMarketStateReq: {
      _this->_internal_mutable_market_state_req()->::market_trader::MarketStateReq::MergeFrom(
          from._internal_market_state_req());
      break;
    }
    case kMarketStateRsp: {
      _this->_internal_mutable_market_state_rsp()->::market_trader::MarketStateRsp::MergeFrom(
          from._internal_market_state_rsp());
      break;
    }
    case MESSAGETYPE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void message::CopyFrom(const message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:market_trader.message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool message::IsInitialized() const {
  return true;
}

void message::InternalSwap(message* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.MessageType_, other->_impl_.MessageType_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata message::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_market_2dtrader_2eproto_getter, &descriptor_table_market_2dtrader_2eproto_once,
      file_level_metadata_market_2dtrader_2eproto[0]);
}

// ===================================================================

class QryInstrumentRsp::_Internal {
 public:
};

QryInstrumentRsp::QryInstrumentRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:market_trader.QryInstrumentRsp)
}
QryInstrumentRsp::QryInstrumentRsp(const QryInstrumentRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  QryInstrumentRsp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.instrument_id_){}
    , decltype(_impl_.exchange_id_){}
    , decltype(_impl_.result_){}
    , decltype(_impl_.finish_flag_){}
    , decltype(_impl_.is_trade_){}
    , decltype(_impl_.ticksize_){}
    , decltype(_impl_.tradeuint_){}
    , decltype(_impl_.min_limit_volume_){}
    , decltype(_impl_.max_limit_volume_){}
    , decltype(_impl_.min_market_volume_){}
    , decltype(_impl_.max_market_volume_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.instrument_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instrument_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_instrument_id().empty()) {
    _this->_impl_.instrument_id_.Set(from._internal_instrument_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.exchange_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.exchange_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_exchange_id().empty()) {
    _this->_impl_.exchange_id_.Set(from._internal_exchange_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.result_, &from._impl_.result_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.max_market_volume_) -
    reinterpret_cast<char*>(&_impl_.result_)) + sizeof(_impl_.max_market_volume_));
  // @@protoc_insertion_point(copy_constructor:market_trader.QryInstrumentRsp)
}

inline void QryInstrumentRsp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.instrument_id_){}
    , decltype(_impl_.exchange_id_){}
    , decltype(_impl_.result_){0}
    , decltype(_impl_.finish_flag_){false}
    , decltype(_impl_.is_trade_){false}
    , decltype(_impl_.ticksize_){0}
    , decltype(_impl_.tradeuint_){0}
    , decltype(_impl_.min_limit_volume_){0u}
    , decltype(_impl_.max_limit_volume_){0u}
    , decltype(_impl_.min_market_volume_){0u}
    , decltype(_impl_.max_market_volume_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.instrument_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instrument_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.exchange_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.exchange_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

QryInstrumentRsp::~QryInstrumentRsp() {
  // @@protoc_insertion_point(destructor:market_trader.QryInstrumentRsp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void QryInstrumentRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.instrument_id_.Destroy();
  _impl_.exchange_id_.Destroy();
}

void QryInstrumentRsp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void QryInstrumentRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:market_trader.QryInstrumentRsp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.instrument_id_.ClearToEmpty();
  _impl_.exchange_id_.ClearToEmpty();
  ::memset(&_impl_.result_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.max_market_volume_) -
      reinterpret_cast<char*>(&_impl_.result_)) + sizeof(_impl_.max_market_volume_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* QryInstrumentRsp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .market_trader.Result result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_result(static_cast<::market_trader::Result>(val));
        } else
          goto handle_unusual;
        continue;
      // bool finish_flag = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.finish_flag_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string instrument_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_instrument_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "market_trader.QryInstrumentRsp.instrument_id"));
        } else
          goto handle_unusual;
        continue;
      // string exchange_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_exchange_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "market_trader.QryInstrumentRsp.exchange_id"));
        } else
          goto handle_unusual;
        continue;
      // double ticksize = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.ticksize_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double tradeuint = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.tradeuint_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // uint32 min_limit_volume = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.min_limit_volume_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 max_limit_volume = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.max_limit_volume_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 min_market_volume = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.min_market_volume_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 max_market_volume = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.max_market_volume_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_trade = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_.is_trade_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* QryInstrumentRsp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:market_trader.QryInstrumentRsp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .market_trader.Result result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_result(), target);
  }

  // bool finish_flag = 2;
  if (this->_internal_finish_flag() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_finish_flag(), target);
  }

  // string instrument_id = 3;
  if (!this->_internal_instrument_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_instrument_id().data(), static_cast<int>(this->_internal_instrument_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "market_trader.QryInstrumentRsp.instrument_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_instrument_id(), target);
  }

  // string exchange_id = 4;
  if (!this->_internal_exchange_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_exchange_id().data(), static_cast<int>(this->_internal_exchange_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "market_trader.QryInstrumentRsp.exchange_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_exchange_id(), target);
  }

  // double ticksize = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_ticksize = this->_internal_ticksize();
  uint64_t raw_ticksize;
  memcpy(&raw_ticksize, &tmp_ticksize, sizeof(tmp_ticksize));
  if (raw_ticksize != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_ticksize(), target);
  }

  // double tradeuint = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tradeuint = this->_internal_tradeuint();
  uint64_t raw_tradeuint;
  memcpy(&raw_tradeuint, &tmp_tradeuint, sizeof(tmp_tradeuint));
  if (raw_tradeuint != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_tradeuint(), target);
  }

  // uint32 min_limit_volume = 7;
  if (this->_internal_min_limit_volume() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_min_limit_volume(), target);
  }

  // uint32 max_limit_volume = 8;
  if (this->_internal_max_limit_volume() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(8, this->_internal_max_limit_volume(), target);
  }

  // uint32 min_market_volume = 9;
  if (this->_internal_min_market_volume() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(9, this->_internal_min_market_volume(), target);
  }

  // uint32 max_market_volume = 10;
  if (this->_internal_max_market_volume() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(10, this->_internal_max_market_volume(), target);
  }

  // bool is_trade = 11;
  if (this->_internal_is_trade() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(11, this->_internal_is_trade(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:market_trader.QryInstrumentRsp)
  return target;
}

size_t QryInstrumentRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:market_trader.QryInstrumentRsp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string instrument_id = 3;
  if (!this->_internal_instrument_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_instrument_id());
  }

  // string exchange_id = 4;
  if (!this->_internal_exchange_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_exchange_id());
  }

  // .market_trader.Result result = 1;
  if (this->_internal_result() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_result());
  }

  // bool finish_flag = 2;
  if (this->_internal_finish_flag() != 0) {
    total_size += 1 + 1;
  }

  // bool is_trade = 11;
  if (this->_internal_is_trade() != 0) {
    total_size += 1 + 1;
  }

  // double ticksize = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_ticksize = this->_internal_ticksize();
  uint64_t raw_ticksize;
  memcpy(&raw_ticksize, &tmp_ticksize, sizeof(tmp_ticksize));
  if (raw_ticksize != 0) {
    total_size += 1 + 8;
  }

  // double tradeuint = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tradeuint = this->_internal_tradeuint();
  uint64_t raw_tradeuint;
  memcpy(&raw_tradeuint, &tmp_tradeuint, sizeof(tmp_tradeuint));
  if (raw_tradeuint != 0) {
    total_size += 1 + 8;
  }

  // uint32 min_limit_volume = 7;
  if (this->_internal_min_limit_volume() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_min_limit_volume());
  }

  // uint32 max_limit_volume = 8;
  if (this->_internal_max_limit_volume() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_max_limit_volume());
  }

  // uint32 min_market_volume = 9;
  if (this->_internal_min_market_volume() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_min_market_volume());
  }

  // uint32 max_market_volume = 10;
  if (this->_internal_max_market_volume() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_max_market_volume());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData QryInstrumentRsp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    QryInstrumentRsp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*QryInstrumentRsp::GetClassData() const { return &_class_data_; }


void QryInstrumentRsp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<QryInstrumentRsp*>(&to_msg);
  auto& from = static_cast<const QryInstrumentRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:market_trader.QryInstrumentRsp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_instrument_id().empty()) {
    _this->_internal_set_instrument_id(from._internal_instrument_id());
  }
  if (!from._internal_exchange_id().empty()) {
    _this->_internal_set_exchange_id(from._internal_exchange_id());
  }
  if (from._internal_result() != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  if (from._internal_finish_flag() != 0) {
    _this->_internal_set_finish_flag(from._internal_finish_flag());
  }
  if (from._internal_is_trade() != 0) {
    _this->_internal_set_is_trade(from._internal_is_trade());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_ticksize = from._internal_ticksize();
  uint64_t raw_ticksize;
  memcpy(&raw_ticksize, &tmp_ticksize, sizeof(tmp_ticksize));
  if (raw_ticksize != 0) {
    _this->_internal_set_ticksize(from._internal_ticksize());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tradeuint = from._internal_tradeuint();
  uint64_t raw_tradeuint;
  memcpy(&raw_tradeuint, &tmp_tradeuint, sizeof(tmp_tradeuint));
  if (raw_tradeuint != 0) {
    _this->_internal_set_tradeuint(from._internal_tradeuint());
  }
  if (from._internal_min_limit_volume() != 0) {
    _this->_internal_set_min_limit_volume(from._internal_min_limit_volume());
  }
  if (from._internal_max_limit_volume() != 0) {
    _this->_internal_set_max_limit_volume(from._internal_max_limit_volume());
  }
  if (from._internal_min_market_volume() != 0) {
    _this->_internal_set_min_market_volume(from._internal_min_market_volume());
  }
  if (from._internal_max_market_volume() != 0) {
    _this->_internal_set_max_market_volume(from._internal_max_market_volume());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void QryInstrumentRsp::CopyFrom(const QryInstrumentRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:market_trader.QryInstrumentRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QryInstrumentRsp::IsInitialized() const {
  return true;
}

void QryInstrumentRsp::InternalSwap(QryInstrumentRsp* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.instrument_id_, lhs_arena,
      &other->_impl_.instrument_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.exchange_id_, lhs_arena,
      &other->_impl_.exchange_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(QryInstrumentRsp, _impl_.max_market_volume_)
      + sizeof(QryInstrumentRsp::_impl_.max_market_volume_)
      - PROTOBUF_FIELD_OFFSET(QryInstrumentRsp, _impl_.result_)>(
          reinterpret_cast<char*>(&_impl_.result_),
          reinterpret_cast<char*>(&other->_impl_.result_));
}

::PROTOBUF_NAMESPACE_ID::Metadata QryInstrumentRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_market_2dtrader_2eproto_getter, &descriptor_table_market_2dtrader_2eproto_once,
      file_level_metadata_market_2dtrader_2eproto[1]);
}

// ===================================================================

class QryInstrumentReq::_Internal {
 public:
};

QryInstrumentReq::QryInstrumentReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:market_trader.QryInstrumentReq)
}
QryInstrumentReq::QryInstrumentReq(const QryInstrumentReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  QryInstrumentReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.identity_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.identity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.identity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_identity().empty()) {
    _this->_impl_.identity_.Set(from._internal_identity(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:market_trader.QryInstrumentReq)
}

inline void QryInstrumentReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.identity_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.identity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.identity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

QryInstrumentReq::~QryInstrumentReq() {
  // @@protoc_insertion_point(destructor:market_trader.QryInstrumentReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void QryInstrumentReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.identity_.Destroy();
}

void QryInstrumentReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void QryInstrumentReq::Clear() {
// @@protoc_insertion_point(message_clear_start:market_trader.QryInstrumentReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.identity_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* QryInstrumentReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string identity = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_identity();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "market_trader.QryInstrumentReq.identity"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* QryInstrumentReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:market_trader.QryInstrumentReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string identity = 1;
  if (!this->_internal_identity().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_identity().data(), static_cast<int>(this->_internal_identity().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "market_trader.QryInstrumentReq.identity");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_identity(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:market_trader.QryInstrumentReq)
  return target;
}

size_t QryInstrumentReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:market_trader.QryInstrumentReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string identity = 1;
  if (!this->_internal_identity().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_identity());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData QryInstrumentReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    QryInstrumentReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*QryInstrumentReq::GetClassData() const { return &_class_data_; }


void QryInstrumentReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<QryInstrumentReq*>(&to_msg);
  auto& from = static_cast<const QryInstrumentReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:market_trader.QryInstrumentReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_identity().empty()) {
    _this->_internal_set_identity(from._internal_identity());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void QryInstrumentReq::CopyFrom(const QryInstrumentReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:market_trader.QryInstrumentReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QryInstrumentReq::IsInitialized() const {
  return true;
}

void QryInstrumentReq::InternalSwap(QryInstrumentReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.identity_, lhs_arena,
      &other->_impl_.identity_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata QryInstrumentReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_market_2dtrader_2eproto_getter, &descriptor_table_market_2dtrader_2eproto_once,
      file_level_metadata_market_2dtrader_2eproto[2]);
}

// ===================================================================

class ActiveInstrumentRsp::_Internal {
 public:
};

ActiveInstrumentRsp::ActiveInstrumentRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:market_trader.ActiveInstrumentRsp)
}
ActiveInstrumentRsp::ActiveInstrumentRsp(const ActiveInstrumentRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ActiveInstrumentRsp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.instrumens_){}
    , decltype(_impl_.exchangeid_){}
    , decltype(_impl_.bislast_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.instrumens_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instrumens_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_instrumens().empty()) {
    _this->_impl_.instrumens_.Set(from._internal_instrumens(), 
      _this->GetArenaForAllocation());
  }
  _impl_.exchangeid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.exchangeid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_exchangeid().empty()) {
    _this->_impl_.exchangeid_.Set(from._internal_exchangeid(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.bislast_ = from._impl_.bislast_;
  // @@protoc_insertion_point(copy_constructor:market_trader.ActiveInstrumentRsp)
}

inline void ActiveInstrumentRsp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.instrumens_){}
    , decltype(_impl_.exchangeid_){}
    , decltype(_impl_.bislast_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.instrumens_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instrumens_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.exchangeid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.exchangeid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ActiveInstrumentRsp::~ActiveInstrumentRsp() {
  // @@protoc_insertion_point(destructor:market_trader.ActiveInstrumentRsp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ActiveInstrumentRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.instrumens_.Destroy();
  _impl_.exchangeid_.Destroy();
}

void ActiveInstrumentRsp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ActiveInstrumentRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:market_trader.ActiveInstrumentRsp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.instrumens_.ClearToEmpty();
  _impl_.exchangeid_.ClearToEmpty();
  _impl_.bislast_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActiveInstrumentRsp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string instrumens = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_instrumens();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "market_trader.ActiveInstrumentRsp.instrumens"));
        } else
          goto handle_unusual;
        continue;
      // string ExchangeID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_exchangeid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "market_trader.ActiveInstrumentRsp.ExchangeID"));
        } else
          goto handle_unusual;
        continue;
      // uint32 bIsLast = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.bislast_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ActiveInstrumentRsp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:market_trader.ActiveInstrumentRsp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string instrumens = 1;
  if (!this->_internal_instrumens().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_instrumens().data(), static_cast<int>(this->_internal_instrumens().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "market_trader.ActiveInstrumentRsp.instrumens");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_instrumens(), target);
  }

  // string ExchangeID = 2;
  if (!this->_internal_exchangeid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_exchangeid().data(), static_cast<int>(this->_internal_exchangeid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "market_trader.ActiveInstrumentRsp.ExchangeID");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_exchangeid(), target);
  }

  // uint32 bIsLast = 3;
  if (this->_internal_bislast() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_bislast(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:market_trader.ActiveInstrumentRsp)
  return target;
}

size_t ActiveInstrumentRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:market_trader.ActiveInstrumentRsp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string instrumens = 1;
  if (!this->_internal_instrumens().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_instrumens());
  }

  // string ExchangeID = 2;
  if (!this->_internal_exchangeid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_exchangeid());
  }

  // uint32 bIsLast = 3;
  if (this->_internal_bislast() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_bislast());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActiveInstrumentRsp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ActiveInstrumentRsp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActiveInstrumentRsp::GetClassData() const { return &_class_data_; }


void ActiveInstrumentRsp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ActiveInstrumentRsp*>(&to_msg);
  auto& from = static_cast<const ActiveInstrumentRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:market_trader.ActiveInstrumentRsp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_instrumens().empty()) {
    _this->_internal_set_instrumens(from._internal_instrumens());
  }
  if (!from._internal_exchangeid().empty()) {
    _this->_internal_set_exchangeid(from._internal_exchangeid());
  }
  if (from._internal_bislast() != 0) {
    _this->_internal_set_bislast(from._internal_bislast());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActiveInstrumentRsp::CopyFrom(const ActiveInstrumentRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:market_trader.ActiveInstrumentRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActiveInstrumentRsp::IsInitialized() const {
  return true;
}

void ActiveInstrumentRsp::InternalSwap(ActiveInstrumentRsp* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.instrumens_, lhs_arena,
      &other->_impl_.instrumens_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.exchangeid_, lhs_arena,
      &other->_impl_.exchangeid_, rhs_arena
  );
  swap(_impl_.bislast_, other->_impl_.bislast_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ActiveInstrumentRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_market_2dtrader_2eproto_getter, &descriptor_table_market_2dtrader_2eproto_once,
      file_level_metadata_market_2dtrader_2eproto[3]);
}

// ===================================================================

class ActiveInstrumentReq::_Internal {
 public:
};

ActiveInstrumentReq::ActiveInstrumentReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:market_trader.ActiveInstrumentReq)
}
ActiveInstrumentReq::ActiveInstrumentReq(const ActiveInstrumentReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ActiveInstrumentReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.instrument_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.instrument_type_ = from._impl_.instrument_type_;
  // @@protoc_insertion_point(copy_constructor:market_trader.ActiveInstrumentReq)
}

inline void ActiveInstrumentReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.instrument_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ActiveInstrumentReq::~ActiveInstrumentReq() {
  // @@protoc_insertion_point(destructor:market_trader.ActiveInstrumentReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ActiveInstrumentReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ActiveInstrumentReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ActiveInstrumentReq::Clear() {
// @@protoc_insertion_point(message_clear_start:market_trader.ActiveInstrumentReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.instrument_type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActiveInstrumentReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .market_trader.ActiveInstrumentReq.InstrumentType instrument_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_instrument_type(static_cast<::market_trader::ActiveInstrumentReq_InstrumentType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ActiveInstrumentReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:market_trader.ActiveInstrumentReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .market_trader.ActiveInstrumentReq.InstrumentType instrument_type = 1;
  if (this->_internal_instrument_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_instrument_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:market_trader.ActiveInstrumentReq)
  return target;
}

size_t ActiveInstrumentReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:market_trader.ActiveInstrumentReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .market_trader.ActiveInstrumentReq.InstrumentType instrument_type = 1;
  if (this->_internal_instrument_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_instrument_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActiveInstrumentReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ActiveInstrumentReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActiveInstrumentReq::GetClassData() const { return &_class_data_; }


void ActiveInstrumentReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ActiveInstrumentReq*>(&to_msg);
  auto& from = static_cast<const ActiveInstrumentReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:market_trader.ActiveInstrumentReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_instrument_type() != 0) {
    _this->_internal_set_instrument_type(from._internal_instrument_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActiveInstrumentReq::CopyFrom(const ActiveInstrumentReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:market_trader.ActiveInstrumentReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActiveInstrumentReq::IsInitialized() const {
  return true;
}

void ActiveInstrumentReq::InternalSwap(ActiveInstrumentReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.instrument_type_, other->_impl_.instrument_type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ActiveInstrumentReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_market_2dtrader_2eproto_getter, &descriptor_table_market_2dtrader_2eproto_once,
      file_level_metadata_market_2dtrader_2eproto[4]);
}

// ===================================================================

class MarketStateReq::_Internal {
 public:
};

MarketStateReq::MarketStateReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:market_trader.MarketStateReq)
}
MarketStateReq::MarketStateReq(const MarketStateReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MarketStateReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.date_){}
    , decltype(_impl_.market_state_){}
    , decltype(_impl_.is_last_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.date_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.date_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_date().empty()) {
    _this->_impl_.date_.Set(from._internal_date(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.market_state_, &from._impl_.market_state_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_last_) -
    reinterpret_cast<char*>(&_impl_.market_state_)) + sizeof(_impl_.is_last_));
  // @@protoc_insertion_point(copy_constructor:market_trader.MarketStateReq)
}

inline void MarketStateReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.date_){}
    , decltype(_impl_.market_state_){0}
    , decltype(_impl_.is_last_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.date_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.date_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MarketStateReq::~MarketStateReq() {
  // @@protoc_insertion_point(destructor:market_trader.MarketStateReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MarketStateReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.date_.Destroy();
}

void MarketStateReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MarketStateReq::Clear() {
// @@protoc_insertion_point(message_clear_start:market_trader.MarketStateReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.date_.ClearToEmpty();
  ::memset(&_impl_.market_state_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_last_) -
      reinterpret_cast<char*>(&_impl_.market_state_)) + sizeof(_impl_.is_last_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MarketStateReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .market_trader.MarketStateReq.MarketState market_state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_market_state(static_cast<::market_trader::MarketStateReq_MarketState>(val));
        } else
          goto handle_unusual;
        continue;
      // string date = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_date();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "market_trader.MarketStateReq.date"));
        } else
          goto handle_unusual;
        continue;
      // bool is_last = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.is_last_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MarketStateReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:market_trader.MarketStateReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .market_trader.MarketStateReq.MarketState market_state = 1;
  if (this->_internal_market_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_market_state(), target);
  }

  // string date = 2;
  if (!this->_internal_date().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_date().data(), static_cast<int>(this->_internal_date().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "market_trader.MarketStateReq.date");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_date(), target);
  }

  // bool is_last = 3;
  if (this->_internal_is_last() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_is_last(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:market_trader.MarketStateReq)
  return target;
}

size_t MarketStateReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:market_trader.MarketStateReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string date = 2;
  if (!this->_internal_date().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_date());
  }

  // .market_trader.MarketStateReq.MarketState market_state = 1;
  if (this->_internal_market_state() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_market_state());
  }

  // bool is_last = 3;
  if (this->_internal_is_last() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MarketStateReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MarketStateReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MarketStateReq::GetClassData() const { return &_class_data_; }


void MarketStateReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MarketStateReq*>(&to_msg);
  auto& from = static_cast<const MarketStateReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:market_trader.MarketStateReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_date().empty()) {
    _this->_internal_set_date(from._internal_date());
  }
  if (from._internal_market_state() != 0) {
    _this->_internal_set_market_state(from._internal_market_state());
  }
  if (from._internal_is_last() != 0) {
    _this->_internal_set_is_last(from._internal_is_last());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MarketStateReq::CopyFrom(const MarketStateReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:market_trader.MarketStateReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MarketStateReq::IsInitialized() const {
  return true;
}

void MarketStateReq::InternalSwap(MarketStateReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.date_, lhs_arena,
      &other->_impl_.date_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MarketStateReq, _impl_.is_last_)
      + sizeof(MarketStateReq::_impl_.is_last_)
      - PROTOBUF_FIELD_OFFSET(MarketStateReq, _impl_.market_state_)>(
          reinterpret_cast<char*>(&_impl_.market_state_),
          reinterpret_cast<char*>(&other->_impl_.market_state_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MarketStateReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_market_2dtrader_2eproto_getter, &descriptor_table_market_2dtrader_2eproto_once,
      file_level_metadata_market_2dtrader_2eproto[5]);
}

// ===================================================================

class MarketStateRsp::_Internal {
 public:
};

MarketStateRsp::MarketStateRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:market_trader.MarketStateRsp)
}
MarketStateRsp::MarketStateRsp(const MarketStateRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MarketStateRsp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.result_ = from._impl_.result_;
  // @@protoc_insertion_point(copy_constructor:market_trader.MarketStateRsp)
}

inline void MarketStateRsp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MarketStateRsp::~MarketStateRsp() {
  // @@protoc_insertion_point(destructor:market_trader.MarketStateRsp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MarketStateRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MarketStateRsp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MarketStateRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:market_trader.MarketStateRsp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MarketStateRsp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MarketStateRsp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:market_trader.MarketStateRsp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_result(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:market_trader.MarketStateRsp)
  return target;
}

size_t MarketStateRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:market_trader.MarketStateRsp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 result = 1;
  if (this->_internal_result() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MarketStateRsp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MarketStateRsp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MarketStateRsp::GetClassData() const { return &_class_data_; }


void MarketStateRsp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MarketStateRsp*>(&to_msg);
  auto& from = static_cast<const MarketStateRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:market_trader.MarketStateRsp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MarketStateRsp::CopyFrom(const MarketStateRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:market_trader.MarketStateRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MarketStateRsp::IsInitialized() const {
  return true;
}

void MarketStateRsp::InternalSwap(MarketStateRsp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_, other->_impl_.result_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MarketStateRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_market_2dtrader_2eproto_getter, &descriptor_table_market_2dtrader_2eproto_once,
      file_level_metadata_market_2dtrader_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace market_trader
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::market_trader::message*
Arena::CreateMaybeMessage< ::market_trader::message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::market_trader::message >(arena);
}
template<> PROTOBUF_NOINLINE ::market_trader::QryInstrumentRsp*
Arena::CreateMaybeMessage< ::market_trader::QryInstrumentRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::market_trader::QryInstrumentRsp >(arena);
}
template<> PROTOBUF_NOINLINE ::market_trader::QryInstrumentReq*
Arena::CreateMaybeMessage< ::market_trader::QryInstrumentReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::market_trader::QryInstrumentReq >(arena);
}
template<> PROTOBUF_NOINLINE ::market_trader::ActiveInstrumentRsp*
Arena::CreateMaybeMessage< ::market_trader::ActiveInstrumentRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::market_trader::ActiveInstrumentRsp >(arena);
}
template<> PROTOBUF_NOINLINE ::market_trader::ActiveInstrumentReq*
Arena::CreateMaybeMessage< ::market_trader::ActiveInstrumentReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::market_trader::ActiveInstrumentReq >(arena);
}
template<> PROTOBUF_NOINLINE ::market_trader::MarketStateReq*
Arena::CreateMaybeMessage< ::market_trader::MarketStateReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::market_trader::MarketStateReq >(arena);
}
template<> PROTOBUF_NOINLINE ::market_trader::MarketStateRsp*
Arena::CreateMaybeMessage< ::market_trader::MarketStateRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::market_trader::MarketStateRsp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
